import***REMOVED***{***REMOVED***clsx,***REMOVED***type***REMOVED***ClassValue***REMOVED***}***REMOVED***from***REMOVED***"clsx"
import***REMOVED***{***REMOVED***twMerge***REMOVED***}***REMOVED***from***REMOVED***"tailwind-merge"

export***REMOVED***function***REMOVED***cn(...inputs:***REMOVED***ClassValue[])***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***twMerge(clsx(inputs))
}

//***REMOVED***Fonction***REMOVED***pour***REMOVED***formater***REMOVED***l'affiliation/relationship_type
export***REMOVED***const***REMOVED***formatRelationshipType***REMOVED***=***REMOVED***(relationshipType:***REMOVED***string):***REMOVED***string***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***relationshipMap:***REMOVED***Record<string,***REMOVED***string>***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***'fils':***REMOVED***'Fils',
***REMOVED******REMOVED******REMOVED******REMOVED***'fille':***REMOVED***'Fille',
***REMOVED******REMOVED******REMOVED******REMOVED***'père':***REMOVED***'Père',
***REMOVED******REMOVED******REMOVED******REMOVED***'mère':***REMOVED***'Mère',
***REMOVED******REMOVED******REMOVED******REMOVED***'cousin':***REMOVED***'Cousin',
***REMOVED******REMOVED******REMOVED******REMOVED***'cousine':***REMOVED***'Cousine',
***REMOVED******REMOVED******REMOVED******REMOVED***'tante':***REMOVED***'Tante',
***REMOVED******REMOVED******REMOVED******REMOVED***'oncle':***REMOVED***'Oncle',
***REMOVED******REMOVED******REMOVED******REMOVED***'neveu':***REMOVED***'Neveu',
***REMOVED******REMOVED******REMOVED******REMOVED***'nièce':***REMOVED***'Nièce',
***REMOVED******REMOVED******REMOVED******REMOVED***'petit-fils':***REMOVED***'Petit-fils',
***REMOVED******REMOVED******REMOVED******REMOVED***'petite-fille':***REMOVED***'Petite-fille',
***REMOVED******REMOVED******REMOVED******REMOVED***'grand-père':***REMOVED***'Grand-père',
***REMOVED******REMOVED******REMOVED******REMOVED***'grande-mère':***REMOVED***'Grand-mère',
***REMOVED******REMOVED******REMOVED******REMOVED***'époux':***REMOVED***'Époux',
***REMOVED******REMOVED******REMOVED******REMOVED***'épouse':***REMOVED***'Épouse',
***REMOVED******REMOVED******REMOVED******REMOVED***'patriarche':***REMOVED***'Patriarche',
***REMOVED******REMOVED******REMOVED******REMOVED***'matriarche':***REMOVED***'Matriarche',
***REMOVED******REMOVED******REMOVED******REMOVED***'conjoint':***REMOVED***'Conjoint',
***REMOVED******REMOVED******REMOVED******REMOVED***'beau-fils':***REMOVED***'Beau-fils',
***REMOVED******REMOVED******REMOVED******REMOVED***'belle-fille':***REMOVED***'Belle-fille',
***REMOVED******REMOVED******REMOVED******REMOVED***'beau-père':***REMOVED***'Beau-père',
***REMOVED******REMOVED******REMOVED******REMOVED***'belle-mère':***REMOVED***'Belle-mère',
***REMOVED******REMOVED******REMOVED******REMOVED***'frère':***REMOVED***'Frère',
***REMOVED******REMOVED******REMOVED******REMOVED***'sœur':***REMOVED***'Sœur'
***REMOVED******REMOVED***};

***REMOVED******REMOVED***return***REMOVED***relationshipMap[relationshipType.toLowerCase()]***REMOVED***||***REMOVED***relationshipType;
};
