import***REMOVED***{***REMOVED***z***REMOVED***}***REMOVED***from***REMOVED***'zod';
import***REMOVED***{***REMOVED***RelationshipType,***REMOVED***Civilite,***REMOVED***UserRole***REMOVED***}***REMOVED***from***REMOVED***'@/types/family';

//***REMOVED***Schémas***REMOVED***de***REMOVED***validation***REMOVED***harmonisés
export***REMOVED***const***REMOVED***relationshipTypes:***REMOVED***RelationshipType[]***REMOVED***=***REMOVED***[
***REMOVED******REMOVED***'patriarche',
***REMOVED******REMOVED***'matriarche',
***REMOVED******REMOVED***'conjoint',
***REMOVED******REMOVED***'fils',
***REMOVED******REMOVED***'fille',
***REMOVED******REMOVED***'frere',
***REMOVED******REMOVED***'soeur',
***REMOVED******REMOVED***'pere',
***REMOVED******REMOVED***'mere',
***REMOVED******REMOVED***'grand-pere',
***REMOVED******REMOVED***'grand-mere',
***REMOVED******REMOVED***'petit-fils',
***REMOVED******REMOVED***'petite-fille',
***REMOVED******REMOVED***'oncle',
***REMOVED******REMOVED***'tante',
***REMOVED******REMOVED***'neveu',
***REMOVED******REMOVED***'niece',
***REMOVED******REMOVED***'cousin',
***REMOVED******REMOVED***'cousine',
***REMOVED******REMOVED***'epoux',
***REMOVED******REMOVED***'epouse',
***REMOVED******REMOVED***'beau-pere',
***REMOVED******REMOVED***'belle-mere',
***REMOVED******REMOVED***'beau-fils',
***REMOVED******REMOVED***'belle-fille'
];

export***REMOVED***const***REMOVED***civiliteOptions:***REMOVED***Civilite[]***REMOVED***=***REMOVED***['M.',***REMOVED***'Mme'];
export***REMOVED***const***REMOVED***roleOptions:***REMOVED***UserRole[]***REMOVED***=***REMOVED***['admin',***REMOVED***'user',***REMOVED***'pending'];

export***REMOVED***const***REMOVED***familyMemberSchema***REMOVED***=***REMOVED***z.object({
***REMOVED******REMOVED***first_name:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***prénom***REMOVED***est***REMOVED***requis"),
***REMOVED******REMOVED***last_name:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***nom***REMOVED***est***REMOVED***requis"),
***REMOVED******REMOVED***email:***REMOVED***z.string().email("Email***REMOVED***invalide"),
***REMOVED******REMOVED***civilite:***REMOVED***z.enum(['M.',***REMOVED***'Mme']),
***REMOVED******REMOVED***phone:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***profession:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***current_location:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***birth_place:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***birth_date:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***avatar_url:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***photo_url:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***relationship_type:***REMOVED***z.enum(relationshipTypes***REMOVED***as***REMOVED***[RelationshipType,***REMOVED***...RelationshipType[]]),
***REMOVED******REMOVED***father_id:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***mother_id:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***situation:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***role:***REMOVED***z.enum(['admin',***REMOVED***'user',***REMOVED***'pending']).default('pending')
});

export***REMOVED***const***REMOVED***familyRegisterSchema***REMOVED***=***REMOVED***z.object({
***REMOVED******REMOVED***first_name:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***prénom***REMOVED***est***REMOVED***requis"),
***REMOVED******REMOVED***last_name:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***nom***REMOVED***est***REMOVED***requis"),
***REMOVED******REMOVED***email:***REMOVED***z.string().email("Email***REMOVED***invalide"),
***REMOVED******REMOVED***password:***REMOVED***z.string().min(6,***REMOVED***"Le***REMOVED***mot***REMOVED***de***REMOVED***passe***REMOVED***doit***REMOVED***contenir***REMOVED***au***REMOVED***moins***REMOVED***6***REMOVED***caractères"),
***REMOVED******REMOVED***civilite:***REMOVED***z.enum(['M.',***REMOVED***'Mme']),
***REMOVED******REMOVED***phone:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***profession:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***current_location:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***birth_place:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***birth_date:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***photo_url:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***relationship_type:***REMOVED***z.enum(relationshipTypes***REMOVED***as***REMOVED***[RelationshipType,***REMOVED***...RelationshipType[]]),
***REMOVED******REMOVED***situation:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***role:***REMOVED***z.enum(['Membre',***REMOVED***'Administrateur']).default('Membre')
});

export***REMOVED***const***REMOVED***loginSchema***REMOVED***=***REMOVED***z.object({
***REMOVED******REMOVED***email:***REMOVED***z.string().email("Email***REMOVED***invalide"),
***REMOVED******REMOVED***password:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***mot***REMOVED***de***REMOVED***passe***REMOVED***est***REMOVED***requis")
});

export***REMOVED***type***REMOVED***FamilyMemberFormData***REMOVED***=***REMOVED***z.infer<typeof***REMOVED***familyMemberSchema>;
export***REMOVED***type***REMOVED***FamilyRegisterFormData***REMOVED***=***REMOVED***z.infer<typeof***REMOVED***familyRegisterSchema>;
export***REMOVED***type***REMOVED***LoginFormData***REMOVED***=***REMOVED***z.infer<typeof***REMOVED***loginSchema>;
