import***REMOVED***{***REMOVED***z***REMOVED***}***REMOVED***from***REMOVED***'zod';
import***REMOVED***{***REMOVED***RelationshipType***REMOVED***}***REMOVED***from***REMOVED***'@/types/family';

export***REMOVED***const***REMOVED***familyRegisterSchema***REMOVED***=***REMOVED***z.object({
***REMOVED******REMOVED***civilite:***REMOVED***z.enum(['M.',***REMOVED***'Mme']),
***REMOVED******REMOVED***firstName:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***prénom***REMOVED***est***REMOVED***requis"),
***REMOVED******REMOVED***lastName:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***nom***REMOVED***est***REMOVED***requis"),
***REMOVED******REMOVED***email:***REMOVED***z.string().email("Email***REMOVED***invalide"),
***REMOVED******REMOVED***password:***REMOVED***z.string().min(6,***REMOVED***"Mot***REMOVED***de***REMOVED***passe***REMOVED***minimum***REMOVED***6***REMOVED***caractères"),
***REMOVED******REMOVED***phoneCode:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***phone:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***profession:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***currentLocation:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***birthPlace:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***photoUrl:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***relationship:***REMOVED***z.enum(['fils/fille',***REMOVED***'cousin/cousine',***REMOVED***'oncle/tante',***REMOVED***'petit-fils/petite-fille',***REMOVED***'neveux/nièce',***REMOVED***'conjoint',***REMOVED***'père/mère',***REMOVED***'patriarche',***REMOVED***'grand-parent',***REMOVED***'frère/sœur',***REMOVED***'époux/épouse']***REMOVED***as***REMOVED***const),
***REMOVED******REMOVED***spouseName:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***fatherName:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***motherName:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***birthDate:***REMOVED***z.string().optional(),
});

export***REMOVED***const***REMOVED***familyRegistrationSchema***REMOVED***=***REMOVED***z.object({
***REMOVED******REMOVED***email:***REMOVED***z.string().email("Veuillez***REMOVED***entrer***REMOVED***une***REMOVED***adresse***REMOVED***email***REMOVED***valide"),
***REMOVED******REMOVED***password:***REMOVED***z.string().min(4,***REMOVED***"Le***REMOVED***mot***REMOVED***de***REMOVED***passe***REMOVED***doit***REMOVED***contenir***REMOVED***au***REMOVED***moins***REMOVED***4***REMOVED***caractères"),
***REMOVED******REMOVED***firstName:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***prénom***REMOVED***est***REMOVED***requis"),
***REMOVED******REMOVED***lastName:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***nom***REMOVED***est***REMOVED***requis"),
***REMOVED******REMOVED***phone:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***country:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***birthDate:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***birthPlace:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***currentLocation:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***civilite:***REMOVED***z.string().min(1,***REMOVED***"La***REMOVED***civilité***REMOVED***est***REMOVED***requise"),
***REMOVED******REMOVED***situation:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***profession:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***photoUrl:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***father_id:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***mother_id:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***isAdmin:***REMOVED***z.boolean().default(false),
});

export***REMOVED***const***REMOVED***loginSchema***REMOVED***=***REMOVED***z.object({
***REMOVED******REMOVED***email:***REMOVED***z.string().email("Veuillez***REMOVED***entrer***REMOVED***une***REMOVED***adresse***REMOVED***email***REMOVED***valide"),
***REMOVED******REMOVED***password:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***mot***REMOVED***de***REMOVED***passe***REMOVED***est***REMOVED***requis"),
});

export***REMOVED***const***REMOVED***updateProfileSchema***REMOVED***=***REMOVED***z.object({
***REMOVED******REMOVED***firstName:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***prénom***REMOVED***est***REMOVED***requis"),
***REMOVED******REMOVED***lastName:***REMOVED***z.string().min(1,***REMOVED***"Le***REMOVED***nom***REMOVED***est***REMOVED***requis"),
***REMOVED******REMOVED***phone:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***country:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***civilite:***REMOVED***z.string().min(1,***REMOVED***"La***REMOVED***civilité***REMOVED***est***REMOVED***requise"),
***REMOVED******REMOVED***birthDate:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***birthPlace:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***currentLocation:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***situation:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***profession:***REMOVED***z.string().optional(),
***REMOVED******REMOVED***photoUrl:***REMOVED***z.string().optional(),
});

export***REMOVED***type***REMOVED***FamilyRegistrationData***REMOVED***=***REMOVED***z.infer<typeof***REMOVED***familyRegistrationSchema>;
export***REMOVED***type***REMOVED***LoginData***REMOVED***=***REMOVED***z.infer<typeof***REMOVED***loginSchema>;
export***REMOVED***type***REMOVED***UpdateProfileData***REMOVED***=***REMOVED***z.infer<typeof***REMOVED***updateProfileSchema>;
