--***REMOVED***CRÉER***REMOVED***DES***REMOVED***TOKENS***REMOVED***MANUELLEMENT***REMOVED***-***REMOVED***Simuler***REMOVED***le***REMOVED***webhook
--***REMOVED***Exécuter***REMOVED***dans***REMOVED***l'éditeur***REMOVED***SQL***REMOVED***de***REMOVED***Supabase

--***REMOVED***1.***REMOVED***Vérifier***REMOVED***l'état***REMOVED***actuel
SELECT***REMOVED***'État***REMOVED***actuel***REMOVED***des***REMOVED***tables:'***REMOVED***as***REMOVED***info;
SELECT***REMOVED***COUNT(*)***REMOVED***as***REMOVED***profiles_count***REMOVED***FROM***REMOVED***profiles;
SELECT***REMOVED***COUNT(*)***REMOVED***as***REMOVED***tokens_count***REMOVED***FROM***REMOVED***dynasty_creation_tokens;
SELECT***REMOVED***COUNT(*)***REMOVED***as***REMOVED***dynasties_count***REMOVED***FROM***REMOVED***dynasties;

--***REMOVED***2.***REMOVED***Obtenir***REMOVED***les***REMOVED***utilisateurs***REMOVED***récents
SELECT
***REMOVED******REMOVED***id,
***REMOVED******REMOVED***email,
***REMOVED******REMOVED***created_at,
***REMOVED******REMOVED***'Utilisateurs***REMOVED***récents'***REMOVED***as***REMOVED***info
FROM***REMOVED***auth.users
ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC
LIMIT***REMOVED***5;

--***REMOVED***3.***REMOVED***Créer***REMOVED***plusieurs***REMOVED***tokens***REMOVED***de***REMOVED***test***REMOVED***avec***REMOVED***différents***REMOVED***session_ids
--***REMOVED***Token***REMOVED***1:***REMOVED***Session***REMOVED***normale
INSERT***REMOVED***INTO***REMOVED***dynasty_creation_tokens***REMOVED***(
***REMOVED******REMOVED***token,
***REMOVED******REMOVED***user_id,
***REMOVED******REMOVED***stripe_session_id,
***REMOVED******REMOVED***status,
***REMOVED******REMOVED***expires_at
)***REMOVED***VALUES***REMOVED***(
***REMOVED******REMOVED***'DYN-MANUAL-001',
***REMOVED******REMOVED***(SELECT***REMOVED***id***REMOVED***FROM***REMOVED***auth.users***REMOVED***ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC***REMOVED***LIMIT***REMOVED***1),
***REMOVED******REMOVED***'cs_test_manual_001',
***REMOVED******REMOVED***'paid',
***REMOVED******REMOVED***NOW()***REMOVED***+***REMOVED***INTERVAL***REMOVED***'24***REMOVED***hours'
)
ON***REMOVED***CONFLICT***REMOVED***(token)***REMOVED***DO***REMOVED***NOTHING;

--***REMOVED***Token***REMOVED***2:***REMOVED***Session***REMOVED***avec***REMOVED***un***REMOVED***autre***REMOVED***utilisateur
INSERT***REMOVED***INTO***REMOVED***dynasty_creation_tokens***REMOVED***(
***REMOVED******REMOVED***token,
***REMOVED******REMOVED***user_id,
***REMOVED******REMOVED***stripe_session_id,
***REMOVED******REMOVED***status,
***REMOVED******REMOVED***expires_at
)***REMOVED***VALUES***REMOVED***(
***REMOVED******REMOVED***'DYN-MANUAL-002',
***REMOVED******REMOVED***(SELECT***REMOVED***id***REMOVED***FROM***REMOVED***auth.users***REMOVED***ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC***REMOVED***LIMIT***REMOVED***1***REMOVED***OFFSET***REMOVED***1),
***REMOVED******REMOVED***'cs_test_manual_002',
***REMOVED******REMOVED***'paid',
***REMOVED******REMOVED***NOW()***REMOVED***+***REMOVED***INTERVAL***REMOVED***'24***REMOVED***hours'
)
ON***REMOVED***CONFLICT***REMOVED***(token)***REMOVED***DO***REMOVED***NOTHING;

--***REMOVED***Token***REMOVED***3:***REMOVED***Session***REMOVED***pour***REMOVED***le***REMOVED***test***REMOVED***principal
INSERT***REMOVED***INTO***REMOVED***dynasty_creation_tokens***REMOVED***(
***REMOVED******REMOVED***token,
***REMOVED******REMOVED***user_id,
***REMOVED******REMOVED***stripe_session_id,
***REMOVED******REMOVED***status,
***REMOVED******REMOVED***expires_at
)***REMOVED***VALUES***REMOVED***(
***REMOVED******REMOVED***'DYN-MANUAL-003',
***REMOVED******REMOVED***(SELECT***REMOVED***id***REMOVED***FROM***REMOVED***auth.users***REMOVED***ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC***REMOVED***LIMIT***REMOVED***1),
***REMOVED******REMOVED***'cs_test_permission_001',***REMOVED***--***REMOVED***Même***REMOVED***session_id***REMOVED***que***REMOVED***dans***REMOVED***le***REMOVED***script***REMOVED***précédent
***REMOVED******REMOVED***'paid',
***REMOVED******REMOVED***NOW()***REMOVED***+***REMOVED***INTERVAL***REMOVED***'24***REMOVED***hours'
)
ON***REMOVED***CONFLICT***REMOVED***(token)***REMOVED***DO***REMOVED***NOTHING;

--***REMOVED***4.***REMOVED***Créer***REMOVED***des***REMOVED***tokens***REMOVED***avec***REMOVED***des***REMOVED***session_ids***REMOVED***aléatoires***REMOVED***pour***REMOVED***tester
INSERT***REMOVED***INTO***REMOVED***dynasty_creation_tokens***REMOVED***(
***REMOVED******REMOVED***token,
***REMOVED******REMOVED***user_id,
***REMOVED******REMOVED***stripe_session_id,
***REMOVED******REMOVED***status,
***REMOVED******REMOVED***expires_at
)***REMOVED***VALUES
***REMOVED******REMOVED***('DYN-RANDOM-001',***REMOVED***(SELECT***REMOVED***id***REMOVED***FROM***REMOVED***auth.users***REMOVED***ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC***REMOVED***LIMIT***REMOVED***1),***REMOVED***'cs_test_random_001',***REMOVED***'paid',***REMOVED***NOW()***REMOVED***+***REMOVED***INTERVAL***REMOVED***'24***REMOVED***hours'),
***REMOVED******REMOVED***('DYN-RANDOM-002',***REMOVED***(SELECT***REMOVED***id***REMOVED***FROM***REMOVED***auth.users***REMOVED***ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC***REMOVED***LIMIT***REMOVED***1),***REMOVED***'cs_test_random_002',***REMOVED***'paid',***REMOVED***NOW()***REMOVED***+***REMOVED***INTERVAL***REMOVED***'24***REMOVED***hours'),
***REMOVED******REMOVED***('DYN-RANDOM-003',***REMOVED***(SELECT***REMOVED***id***REMOVED***FROM***REMOVED***auth.users***REMOVED***ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC***REMOVED***LIMIT***REMOVED***1),***REMOVED***'cs_test_random_003',***REMOVED***'paid',***REMOVED***NOW()***REMOVED***+***REMOVED***INTERVAL***REMOVED***'24***REMOVED***hours')
ON***REMOVED***CONFLICT***REMOVED***(token)***REMOVED***DO***REMOVED***NOTHING;

--***REMOVED***5.***REMOVED***Afficher***REMOVED***tous***REMOVED***les***REMOVED***tokens***REMOVED***créés
SELECT
***REMOVED******REMOVED***token,
***REMOVED******REMOVED***user_id,
***REMOVED******REMOVED***stripe_session_id,
***REMOVED******REMOVED***status,
***REMOVED******REMOVED***created_at,
***REMOVED******REMOVED***expires_at,
***REMOVED******REMOVED***CASE
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***expires_at***REMOVED***<***REMOVED***NOW()***REMOVED***THEN***REMOVED***'EXPIRED'
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***status***REMOVED***=***REMOVED***'paid'***REMOVED***THEN***REMOVED***'READY_FOR_USE'
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***status***REMOVED***=***REMOVED***'pending'***REMOVED***THEN***REMOVED***'WAITING_FOR_PAYMENT'
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***status***REMOVED***=***REMOVED***'used'***REMOVED***THEN***REMOVED***'ALREADY_USED'
***REMOVED******REMOVED******REMOVED******REMOVED***ELSE***REMOVED***'UNKNOWN'
***REMOVED******REMOVED***END***REMOVED***as***REMOVED***token_state
FROM***REMOVED***dynasty_creation_tokens
ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC;

--***REMOVED***6.***REMOVED***URLs***REMOVED***de***REMOVED***test***REMOVED***à***REMOVED***utiliser:
SELECT
***REMOVED******REMOVED***'URLs***REMOVED***de***REMOVED***test:'***REMOVED***as***REMOVED***info,
***REMOVED******REMOVED***'http://localhost:8081/dynasty/checkout/success?session_id=cs_test_manual_001'***REMOVED***as***REMOVED***test_url_1,
***REMOVED******REMOVED***'http://localhost:8081/dynasty/checkout/success?session_id=cs_test_manual_002'***REMOVED***as***REMOVED***test_url_2,
***REMOVED******REMOVED***'http://localhost:8081/dynasty/checkout/success?session_id=cs_test_permission_001'***REMOVED***as***REMOVED***test_url_3,
***REMOVED******REMOVED***'http://localhost:8081/dynasty/checkout/success?session_id=cs_test_random_001'***REMOVED***as***REMOVED***test_url_4;

--***REMOVED***7.***REMOVED***Vérifier***REMOVED***que***REMOVED***les***REMOVED***permissions***REMOVED***sont***REMOVED***correctes
SELECT
***REMOVED******REMOVED***'Permissions***REMOVED***vérifiées'***REMOVED***as***REMOVED***status,
***REMOVED******REMOVED***(SELECT***REMOVED***COUNT(*)***REMOVED***FROM***REMOVED***dynasty_creation_tokens)***REMOVED***as***REMOVED***total_tokens,
***REMOVED******REMOVED***(SELECT***REMOVED***COUNT(*)***REMOVED***FROM***REMOVED***profiles)***REMOVED***as***REMOVED***total_profiles;
