
import***REMOVED***type***REMOVED***{***REMOVED***Config***REMOVED***}***REMOVED***from***REMOVED***"tailwindcss";

export***REMOVED***default***REMOVED***{
	darkMode:***REMOVED***["class"],
	content:***REMOVED***[
		"./pages/**/*.{ts,tsx}",
		"./components/**/*.{ts,tsx}",
		"./app/**/*.{ts,tsx}",
		"./src/**/*.{ts,tsx}",
	],
	prefix:***REMOVED***"",
	theme:***REMOVED***{
		container:***REMOVED***{
			center:***REMOVED***true,
			padding:***REMOVED***'2rem',
			screens:***REMOVED***{
				'2xl':***REMOVED***'1400px'
			}
		},
		extend:***REMOVED***{
			colors:***REMOVED***{
				border:***REMOVED***'hsl(var(--border))',
				input:***REMOVED***'hsl(var(--input))',
				ring:***REMOVED***'hsl(var(--ring))',
				background:***REMOVED***'hsl(var(--background))',
				foreground:***REMOVED***'hsl(var(--foreground))',
				primary:***REMOVED***{
					DEFAULT:***REMOVED***'hsl(var(--primary))',
					foreground:***REMOVED***'hsl(var(--primary-foreground))'
				},
				secondary:***REMOVED***{
					DEFAULT:***REMOVED***'hsl(var(--secondary))',
					foreground:***REMOVED***'hsl(var(--secondary-foreground))'
				},
				destructive:***REMOVED***{
					DEFAULT:***REMOVED***'hsl(var(--destructive))',
					foreground:***REMOVED***'hsl(var(--destructive-foreground))'
				},
				muted:***REMOVED***{
					DEFAULT:***REMOVED***'hsl(var(--muted))',
					foreground:***REMOVED***'hsl(var(--muted-foreground))'
				},
				accent:***REMOVED***{
					DEFAULT:***REMOVED***'hsl(var(--accent))',
					foreground:***REMOVED***'hsl(var(--accent-foreground))'
				},
				popover:***REMOVED***{
					DEFAULT:***REMOVED***'hsl(var(--popover))',
					foreground:***REMOVED***'hsl(var(--popover-foreground))'
				},
				card:***REMOVED***{
					DEFAULT:***REMOVED***'hsl(var(--card))',
					foreground:***REMOVED***'hsl(var(--card-foreground))'
				},
				sidebar:***REMOVED***{
					DEFAULT:***REMOVED***'hsl(var(--sidebar-background))',
					foreground:***REMOVED***'hsl(var(--sidebar-foreground))',
					primary:***REMOVED***'hsl(var(--sidebar-primary))',
					'primary-foreground':***REMOVED***'hsl(var(--sidebar-primary-foreground))',
					accent:***REMOVED***'hsl(var(--sidebar-accent))',
					'accent-foreground':***REMOVED***'hsl(var(--sidebar-accent-foreground))',
					border:***REMOVED***'hsl(var(--sidebar-border))',
					ring:***REMOVED***'hsl(var(--sidebar-ring))'
				},
				whatsapp:***REMOVED***{
					100:***REMOVED***'#F0F9FF',
					200:***REMOVED***'#E0F2FE',
					300:***REMOVED***'#7DD3FC',
					400:***REMOVED***'#38BDF8',
					500:***REMOVED***'#25D366',
					600:***REMOVED***'#16A249',
					700:***REMOVED***'#0D8236',
					800:***REMOVED***'#166534',
					900:***REMOVED***'#14532D'
				},
				family:***REMOVED***{
					patriarch:***REMOVED***'#FFD700',
					'patriarch-dark':***REMOVED***'#B8860B',
					member:***REMOVED***'#22C55E',
					'member-dark':***REMOVED***'#16A34A',
					admin:***REMOVED***'#3B82F6',
					'admin-dark':***REMOVED***'#1D4ED8'
				}
			},
			borderRadius:***REMOVED***{
				lg:***REMOVED***'var(--radius)',
				md:***REMOVED***'calc(var(--radius)***REMOVED***-***REMOVED***2px)',
				sm:***REMOVED***'calc(var(--radius)***REMOVED***-***REMOVED***4px)'
			},
			keyframes:***REMOVED***{
				'accordion-down':***REMOVED***{
					from:***REMOVED***{
						height:***REMOVED***'0'
					},
					to:***REMOVED***{
						height:***REMOVED***'var(--radix-accordion-content-height)'
					}
				},
				'accordion-up':***REMOVED***{
					from:***REMOVED***{
						height:***REMOVED***'var(--radix-accordion-content-height)'
					},
					to:***REMOVED***{
						height:***REMOVED***'0'
					}
				},
				'fade-in':***REMOVED***{
					'0%':***REMOVED***{***REMOVED***opacity:***REMOVED***'0',***REMOVED***transform:***REMOVED***'translateY(10px)'***REMOVED***},
					'100%':***REMOVED***{***REMOVED***opacity:***REMOVED***'1',***REMOVED***transform:***REMOVED***'translateY(0)'***REMOVED***}
				},
				'bounce-in':***REMOVED***{
					'0%':***REMOVED***{***REMOVED***transform:***REMOVED***'scale(0.8)',***REMOVED***opacity:***REMOVED***'0'***REMOVED***},
					'50%':***REMOVED***{***REMOVED***transform:***REMOVED***'scale(1.05)',***REMOVED***opacity:***REMOVED***'1'***REMOVED***},
					'100%':***REMOVED***{***REMOVED***transform:***REMOVED***'scale(1)',***REMOVED***opacity:***REMOVED***'1'***REMOVED***}
				}
			},
			animation:***REMOVED***{
				'accordion-down':***REMOVED***'accordion-down***REMOVED***0.2s***REMOVED***ease-out',
				'accordion-up':***REMOVED***'accordion-up***REMOVED***0.2s***REMOVED***ease-out',
				'fade-in':***REMOVED***'fade-in***REMOVED***0.5s***REMOVED***ease-out',
				'bounce-in':***REMOVED***'bounce-in***REMOVED***0.6s***REMOVED***ease-out'
			}
		}
	},
	plugins:***REMOVED***[require("tailwindcss-animate")],
}***REMOVED***satisfies***REMOVED***Config;
