--***REMOVED***COMPLETE***REMOVED***SYSTEM***REMOVED***TEST***REMOVED***-***REMOVED***Run***REMOVED***this***REMOVED***in***REMOVED***Supabase***REMOVED***SQL***REMOVED***Editor
--***REMOVED***This***REMOVED***script***REMOVED***tests***REMOVED***the***REMOVED***entire***REMOVED***payment***REMOVED***and***REMOVED***dynasty***REMOVED***creation***REMOVED***flow

--***REMOVED***1.***REMOVED***Check***REMOVED***current***REMOVED***user***REMOVED***and***REMOVED***permissions
SELECT
***REMOVED******REMOVED***current_user,
***REMOVED******REMOVED***session_user,
***REMOVED******REMOVED***'Current***REMOVED***database***REMOVED***user'***REMOVED***as***REMOVED***info;

--***REMOVED***2.***REMOVED***Verify***REMOVED***table***REMOVED***structures
SELECT
***REMOVED******REMOVED***table_name,
***REMOVED******REMOVED***COUNT(*)***REMOVED***as***REMOVED***column_count,
***REMOVED******REMOVED***rowsecurity***REMOVED***as***REMOVED***rls_enabled
FROM***REMOVED***information_schema.tables***REMOVED***t
LEFT***REMOVED***JOIN***REMOVED***pg_tables***REMOVED***pt***REMOVED***ON***REMOVED***t.table_name***REMOVED***=***REMOVED***pt.tablename
WHERE***REMOVED***t.table_schema***REMOVED***=***REMOVED***'public'
AND***REMOVED***t.table_name***REMOVED***IN***REMOVED***('profiles',***REMOVED***'dynasty_creation_tokens',***REMOVED***'dynasties')
GROUP***REMOVED***BY***REMOVED***t.table_name,***REMOVED***pt.rowsecurity
ORDER***REMOVED***BY***REMOVED***t.table_name;

--***REMOVED***3.***REMOVED***Check***REMOVED***RLS***REMOVED***policies
SELECT
***REMOVED******REMOVED***schemaname,
***REMOVED******REMOVED***tablename,
***REMOVED******REMOVED***policyname,
***REMOVED******REMOVED***permissive,
***REMOVED******REMOVED***cmd,
***REMOVED******REMOVED***qual,
***REMOVED******REMOVED***with_check
FROM***REMOVED***pg_policies
WHERE***REMOVED***tablename***REMOVED***IN***REMOVED***('profiles',***REMOVED***'dynasty_creation_tokens',***REMOVED***'dynasties')
ORDER***REMOVED***BY***REMOVED***tablename,***REMOVED***policyname;

--***REMOVED***4.***REMOVED***Get***REMOVED***recent***REMOVED***users***REMOVED***for***REMOVED***testing
SELECT
***REMOVED******REMOVED***id,
***REMOVED******REMOVED***email,
***REMOVED******REMOVED***created_at,
***REMOVED******REMOVED***'Recent***REMOVED***users***REMOVED***for***REMOVED***testing'***REMOVED***as***REMOVED***info
FROM***REMOVED***auth.users
ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC
LIMIT***REMOVED***3;

--***REMOVED***5.***REMOVED***Check***REMOVED***existing***REMOVED***data
SELECT
***REMOVED******REMOVED***'profiles'***REMOVED***as***REMOVED***table_name,
***REMOVED******REMOVED***COUNT(*)***REMOVED***as***REMOVED***total_records,
***REMOVED******REMOVED***COUNT(CASE***REMOVED***WHEN***REMOVED***dynasty_id***REMOVED***IS***REMOVED***NOT***REMOVED***NULL***REMOVED***THEN***REMOVED***1***REMOVED***END)***REMOVED***as***REMOVED***with_dynasty,
***REMOVED******REMOVED***COUNT(CASE***REMOVED***WHEN***REMOVED***dynasty_id***REMOVED***IS***REMOVED***NULL***REMOVED***THEN***REMOVED***1***REMOVED***END)***REMOVED***as***REMOVED***without_dynasty
FROM***REMOVED***profiles
UNION***REMOVED***ALL
SELECT
***REMOVED******REMOVED***'dynasty_creation_tokens'***REMOVED***as***REMOVED***table_name,
***REMOVED******REMOVED***COUNT(*)***REMOVED***as***REMOVED***total_records,
***REMOVED******REMOVED***COUNT(CASE***REMOVED***WHEN***REMOVED***status***REMOVED***=***REMOVED***'paid'***REMOVED***THEN***REMOVED***1***REMOVED***END)***REMOVED***as***REMOVED***paid_tokens,
***REMOVED******REMOVED***COUNT(CASE***REMOVED***WHEN***REMOVED***status***REMOVED***=***REMOVED***'pending'***REMOVED***THEN***REMOVED***1***REMOVED***END)***REMOVED***as***REMOVED***pending_tokens
FROM***REMOVED***dynasty_creation_tokens
UNION***REMOVED***ALL
SELECT
***REMOVED******REMOVED***'dynasties'***REMOVED***as***REMOVED***table_name,
***REMOVED******REMOVED***COUNT(*)***REMOVED***as***REMOVED***total_records,
***REMOVED******REMOVED***COUNT(*)***REMOVED***as***REMOVED***total_dynasties,
***REMOVED******REMOVED***0***REMOVED***as***REMOVED***placeholder
FROM***REMOVED***dynasties;

--***REMOVED***6.***REMOVED***Create***REMOVED***test***REMOVED***tokens***REMOVED***for***REMOVED***different***REMOVED***scenarios
--***REMOVED***Get***REMOVED***the***REMOVED***most***REMOVED***recent***REMOVED***user
WITH***REMOVED***recent_user***REMOVED***AS***REMOVED***(
***REMOVED******REMOVED***SELECT***REMOVED***id***REMOVED***FROM***REMOVED***auth.users***REMOVED***ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC***REMOVED***LIMIT***REMOVED***1
)
INSERT***REMOVED***INTO***REMOVED***dynasty_creation_tokens***REMOVED***(
***REMOVED******REMOVED***token,
***REMOVED******REMOVED***user_id,
***REMOVED******REMOVED***stripe_session_id,
***REMOVED******REMOVED***status,
***REMOVED******REMOVED***expires_at
)
SELECT
***REMOVED******REMOVED***'TEST-COMPLETE-001',
***REMOVED******REMOVED***recent_user.id,
***REMOVED******REMOVED***'cs_test_complete_001',
***REMOVED******REMOVED***'paid',
***REMOVED******REMOVED***NOW()***REMOVED***+***REMOVED***INTERVAL***REMOVED***'24***REMOVED***hours'
FROM***REMOVED***recent_user
WHERE***REMOVED***NOT***REMOVED***EXISTS***REMOVED***(
***REMOVED******REMOVED***SELECT***REMOVED***1***REMOVED***FROM***REMOVED***dynasty_creation_tokens
***REMOVED******REMOVED***WHERE***REMOVED***token***REMOVED***=***REMOVED***'TEST-COMPLETE-001'
);

--***REMOVED***7.***REMOVED***Create***REMOVED***another***REMOVED***test***REMOVED***token***REMOVED***with***REMOVED***different***REMOVED***status
WITH***REMOVED***recent_user***REMOVED***AS***REMOVED***(
***REMOVED******REMOVED***SELECT***REMOVED***id***REMOVED***FROM***REMOVED***auth.users***REMOVED***ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC***REMOVED***LIMIT***REMOVED***1
)
INSERT***REMOVED***INTO***REMOVED***dynasty_creation_tokens***REMOVED***(
***REMOVED******REMOVED***token,
***REMOVED******REMOVED***user_id,
***REMOVED******REMOVED***stripe_session_id,
***REMOVED******REMOVED***status,
***REMOVED******REMOVED***expires_at
)
SELECT
***REMOVED******REMOVED***'TEST-COMPLETE-002',
***REMOVED******REMOVED***recent_user.id,
***REMOVED******REMOVED***'cs_test_complete_002',
***REMOVED******REMOVED***'pending',
***REMOVED******REMOVED***NOW()***REMOVED***+***REMOVED***INTERVAL***REMOVED***'24***REMOVED***hours'
FROM***REMOVED***recent_user
WHERE***REMOVED***NOT***REMOVED***EXISTS***REMOVED***(
***REMOVED******REMOVED***SELECT***REMOVED***1***REMOVED***FROM***REMOVED***dynasty_creation_tokens
***REMOVED******REMOVED***WHERE***REMOVED***token***REMOVED***=***REMOVED***'TEST-COMPLETE-002'
);

--***REMOVED***8.***REMOVED***Show***REMOVED***all***REMOVED***test***REMOVED***tokens
SELECT
***REMOVED******REMOVED***token,
***REMOVED******REMOVED***user_id,
***REMOVED******REMOVED***stripe_session_id,
***REMOVED******REMOVED***status,
***REMOVED******REMOVED***created_at,
***REMOVED******REMOVED***expires_at,
***REMOVED******REMOVED***CASE
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***expires_at***REMOVED***<***REMOVED***NOW()***REMOVED***THEN***REMOVED***'EXPIRED'
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***status***REMOVED***=***REMOVED***'paid'***REMOVED***THEN***REMOVED***'READY_FOR_USE'
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***status***REMOVED***=***REMOVED***'pending'***REMOVED***THEN***REMOVED***'WAITING_FOR_PAYMENT'
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***status***REMOVED***=***REMOVED***'used'***REMOVED***THEN***REMOVED***'ALREADY_USED'
***REMOVED******REMOVED******REMOVED******REMOVED***ELSE***REMOVED***'UNKNOWN'
***REMOVED******REMOVED***END***REMOVED***as***REMOVED***token_state
FROM***REMOVED***dynasty_creation_tokens
WHERE***REMOVED***token***REMOVED***LIKE***REMOVED***'TEST-COMPLETE-%'
ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC;

--***REMOVED***9.***REMOVED***Test***REMOVED***URLs***REMOVED***for***REMOVED***manual***REMOVED***testing
SELECT
***REMOVED******REMOVED***'Test***REMOVED***URLs:'***REMOVED***as***REMOVED***info,
***REMOVED******REMOVED***'http://localhost:8081/dynasty/checkout/success?session_id=cs_test_complete_001'***REMOVED***as***REMOVED***test_url_1,
***REMOVED******REMOVED***'http://localhost:8081/dynasty/checkout/success?session_id=cs_test_complete_002'***REMOVED***as***REMOVED***test_url_2;

--***REMOVED***10.***REMOVED***Verify***REMOVED***we***REMOVED***can***REMOVED***read***REMOVED***data***REMOVED***with***REMOVED***current***REMOVED***permissions
SELECT
***REMOVED******REMOVED***'Data***REMOVED***access***REMOVED***test:'***REMOVED***as***REMOVED***info,
***REMOVED******REMOVED***(SELECT***REMOVED***COUNT(*)***REMOVED***FROM***REMOVED***profiles)***REMOVED***as***REMOVED***profiles_count,
***REMOVED******REMOVED***(SELECT***REMOVED***COUNT(*)***REMOVED***FROM***REMOVED***dynasty_creation_tokens)***REMOVED***as***REMOVED***tokens_count,
***REMOVED******REMOVED***(SELECT***REMOVED***COUNT(*)***REMOVED***FROM***REMOVED***dynasties)***REMOVED***as***REMOVED***dynasties_count;

--***REMOVED***11.***REMOVED***Show***REMOVED***sample***REMOVED***profile***REMOVED***data***REMOVED***(if***REMOVED***any***REMOVED***exists)
SELECT
***REMOVED******REMOVED***id,
***REMOVED******REMOVED***user_id,
***REMOVED******REMOVED***email,
***REMOVED******REMOVED***first_name,
***REMOVED******REMOVED***last_name,
***REMOVED******REMOVED***dynasty_id,
***REMOVED******REMOVED***user_role,
***REMOVED******REMOVED***created_at
FROM***REMOVED***profiles
ORDER***REMOVED***BY***REMOVED***created_at***REMOVED***DESC
LIMIT***REMOVED***3;

--***REMOVED***12.***REMOVED***Final***REMOVED***status***REMOVED***report
SELECT
***REMOVED******REMOVED***'SYSTEM***REMOVED***STATUS***REMOVED***REPORT'***REMOVED***as***REMOVED***report_header,
***REMOVED******REMOVED***CASE
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***(SELECT***REMOVED***COUNT(*)***REMOVED***FROM***REMOVED***profiles)***REMOVED***>***REMOVED***0***REMOVED***THEN***REMOVED***'✅***REMOVED***Profiles***REMOVED***table***REMOVED***accessible'
***REMOVED******REMOVED******REMOVED******REMOVED***ELSE***REMOVED***'⚠️***REMOVED***Profiles***REMOVED***table***REMOVED***empty***REMOVED***or***REMOVED***inaccessible'
***REMOVED******REMOVED***END***REMOVED***as***REMOVED***profiles_status,
***REMOVED******REMOVED***CASE
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***(SELECT***REMOVED***COUNT(*)***REMOVED***FROM***REMOVED***dynasty_creation_tokens)***REMOVED***>***REMOVED***0***REMOVED***THEN***REMOVED***'✅***REMOVED***Tokens***REMOVED***table***REMOVED***accessible'
***REMOVED******REMOVED******REMOVED******REMOVED***ELSE***REMOVED***'⚠️***REMOVED***Tokens***REMOVED***table***REMOVED***empty***REMOVED***or***REMOVED***inaccessible'
***REMOVED******REMOVED***END***REMOVED***as***REMOVED***tokens_status,
***REMOVED******REMOVED***CASE
***REMOVED******REMOVED******REMOVED******REMOVED***WHEN***REMOVED***(SELECT***REMOVED***COUNT(*)***REMOVED***FROM***REMOVED***dynasties)***REMOVED***>=***REMOVED***0***REMOVED***THEN***REMOVED***'✅***REMOVED***Dynasties***REMOVED***table***REMOVED***accessible'
***REMOVED******REMOVED******REMOVED******REMOVED***ELSE***REMOVED***'⚠️***REMOVED***Dynasties***REMOVED***table***REMOVED***inaccessible'
***REMOVED******REMOVED***END***REMOVED***as***REMOVED***dynasties_status;
