import { RelationshipType } from '@/lib/validations/familySchema';

export const relationshipTypeOptions: { value: RelationshipType; label: string }[] = [
  { value: 'patriarche', label: 'Patriarche' },
  { value: 'matriarche', label: 'Matriarche' },
  { value: 'pere', label: 'Père' },
  { value: 'mere', label: 'Mère' },
  { value: 'fils', label: 'Fils' },
  { value: 'fille', label: 'Fille' },
  { value: 'frere', label: 'Frère' },
  { value: 'soeur', label: 'Sœur' },
  { value: 'grand-pere', label: 'Grand-père' },
  { value: 'grand-mere', label: 'Grand-mère' },
  { value: 'petit-fils', label: 'Petit-fils' },
  { value: 'petite-fille', label: 'Petite-fille' },
  { value: 'oncle', label: 'Oncle' },
  { value: 'tante', label: 'Tante' },
  { value: 'neveu', label: 'Neveu' },
  { value: 'niece', label: 'Nièce' },
  { value: 'cousin', label: 'Cousin' },
  { value: 'cousine', label: 'Cousine' },
  { value: 'epoux', label: 'Époux' },
  { value: 'epouse', label: 'Épouse' },
  { value: 'beau-pere', label: 'Beau-père' },
  { value: 'belle-mere', label: 'Belle-mère' },
  { value: 'beau-fils', label: 'Beau-fils' },
  { value: 'belle-fille', label: 'Belle-fille' },
  { value: 'conjoint', label: 'Conjoint' },
];
