export***REMOVED***const***REMOVED***ROUTES***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***HOME:***REMOVED***'/',
***REMOVED******REMOVED***AUTH:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***LOGIN:***REMOVED***'/auth-family',
***REMOVED******REMOVED******REMOVED******REMOVED***REGISTER:***REMOVED***'/auth-family',
***REMOVED******REMOVED******REMOVED******REMOVED***FORGOT_PASSWORD:***REMOVED***'/auth-family',
***REMOVED******REMOVED******REMOVED******REMOVED***FAMILY:***REMOVED***'/auth-family',
***REMOVED******REMOVED***},
***REMOVED******REMOVED***DASHBOARD:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***ROOT:***REMOVED***'/dashboard',
***REMOVED******REMOVED******REMOVED******REMOVED***TREE:***REMOVED***'/dashboard/tree',
***REMOVED******REMOVED******REMOVED******REMOVED***MEMBERS:***REMOVED***'/dashboard/members',
***REMOVED******REMOVED******REMOVED******REMOVED***PROFILE:***REMOVED***'/dashboard/profile',
***REMOVED******REMOVED******REMOVED******REMOVED***ADMIN:***REMOVED***'/dashboard/admin',
***REMOVED******REMOVED******REMOVED******REMOVED***INVITE:***REMOVED***'/dashboard/invite',
***REMOVED******REMOVED******REMOVED******REMOVED***MESSAGES:***REMOVED***'/dashboard/messages',
***REMOVED******REMOVED******REMOVED******REMOVED***NOTIFICATIONS:***REMOVED***'/dashboard/notifications',
***REMOVED******REMOVED***},
***REMOVED******REMOVED***PROFILE:***REMOVED***'/profile',
}***REMOVED***as***REMOVED***const;
