
import***REMOVED***React***REMOVED***from***REMOVED***'react';
import***REMOVED***{***REMOVED***useNavigate,***REMOVED***useLocation***REMOVED***}***REMOVED***from***REMOVED***'react-router-dom';
import***REMOVED***{***REMOVED***Button***REMOVED***}***REMOVED***from***REMOVED***'@/components/ui/button';
import***REMOVED***{***REMOVED***useAuth***REMOVED***}***REMOVED***from***REMOVED***'@/hooks/useAuth';
import***REMOVED***{***REMOVED***ROUTES***REMOVED***}***REMOVED***from***REMOVED***'@/lib/constants/routes';
import***REMOVED***{
***REMOVED******REMOVED***TreePine,
***REMOVED******REMOVED***Users,
***REMOVED******REMOVED***UserPlus,
***REMOVED******REMOVED***Settings,
***REMOVED******REMOVED***MessageSquare,
***REMOVED******REMOVED***Calendar,
***REMOVED******REMOVED***Play,
***REMOVED******REMOVED***Shield
}***REMOVED***from***REMOVED***'lucide-react';

interface***REMOVED***NavItem***REMOVED***{
***REMOVED******REMOVED***path:***REMOVED***string;
***REMOVED******REMOVED***label:***REMOVED***string;
***REMOVED******REMOVED***icon:***REMOVED***React.ReactNode;
***REMOVED******REMOVED***requiresAuth?:***REMOVED***boolean;
***REMOVED******REMOVED***adminOnly?:***REMOVED***boolean;
}

export***REMOVED***const***REMOVED***MainNavBar:***REMOVED***React.FC***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***navigate***REMOVED***=***REMOVED***useNavigate();
***REMOVED******REMOVED***const***REMOVED***location***REMOVED***=***REMOVED***useLocation();
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***user,***REMOVED***profile***REMOVED***}***REMOVED***=***REMOVED***useAuth();

***REMOVED******REMOVED***const***REMOVED***navItems:***REMOVED***NavItem[]***REMOVED***=***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.TREE,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Arbre***REMOVED***Familial',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<TreePine***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.MEMBERS,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Membres',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<Users***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.MEDIA,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Médias',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<Play***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.INVITE,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Inviter',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<UserPlus***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.MESSAGES,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Messages',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<MessageSquare***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.EVENTS,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Événements',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<Calendar***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.ADMIN,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Administration',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<Shield***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***adminOnly:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.SETTINGS,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Paramètres',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<Settings***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED***];

***REMOVED******REMOVED***const***REMOVED***isActiveRoute***REMOVED***=***REMOVED***(path:***REMOVED***string)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***location.pathname***REMOVED***===***REMOVED***path;
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***canShowItem***REMOVED***=***REMOVED***(item:***REMOVED***NavItem)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(item.requiresAuth***REMOVED***&&***REMOVED***!user)***REMOVED***return***REMOVED***false;
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(item.adminOnly***REMOVED***&&***REMOVED***profile?.user_role***REMOVED***!==***REMOVED***'Administrateur')***REMOVED***return***REMOVED***false;
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***true;
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***filteredNavItems***REMOVED***=***REMOVED***navItems.filter(canShowItem);

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<nav***REMOVED***className="hidden***REMOVED***md:flex***REMOVED***items-center***REMOVED***space-x-4***REMOVED***overflow-x-auto">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{filteredNavItems.map((item)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={item.path}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant={isActiveRoute(item.path)***REMOVED***?***REMOVED***"default"***REMOVED***:***REMOVED***"ghost"}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size="sm"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={()***REMOVED***=>***REMOVED***navigate(item.path)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={`flex***REMOVED***items-center***REMOVED***space-x-2***REMOVED***whitespace-nowrap***REMOVED***${
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isActiveRoute(item.path)***REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***'bg-whatsapp-600***REMOVED***text-white'***REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***'text-gray-700***REMOVED***hover:text-whatsapp-600'
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}`}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{item.icon}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span>{item.label}</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED***</nav>
***REMOVED******REMOVED***);
};
