
import***REMOVED***React***REMOVED***from***REMOVED***'react';
import***REMOVED***{***REMOVED***useNavigate,***REMOVED***useLocation***REMOVED***}***REMOVED***from***REMOVED***'react-router-dom';
import***REMOVED***{***REMOVED***Button***REMOVED***}***REMOVED***from***REMOVED***'@/components/ui/button';
import***REMOVED***{***REMOVED***useAuth***REMOVED***}***REMOVED***from***REMOVED***'@/hooks/useAuth';
import***REMOVED***{***REMOVED***ROUTES***REMOVED***}***REMOVED***from***REMOVED***'@/lib/constants/routes';
import***REMOVED***{
***REMOVED******REMOVED***Home,
***REMOVED******REMOVED***TreePine,
***REMOVED******REMOVED***Users,
***REMOVED******REMOVED***UserPlus,
***REMOVED******REMOVED***HelpCircle,
***REMOVED******REMOVED***Info,
***REMOVED******REMOVED***LogIn,
***REMOVED******REMOVED***UserCheck,
***REMOVED******REMOVED***Play
}***REMOVED***from***REMOVED***'lucide-react';

interface***REMOVED***NavItem***REMOVED***{
***REMOVED******REMOVED***path:***REMOVED***string;
***REMOVED******REMOVED***label:***REMOVED***string;
***REMOVED******REMOVED***icon:***REMOVED***React.ReactNode;
***REMOVED******REMOVED***requiresAuth?:***REMOVED***boolean;
***REMOVED******REMOVED***publicOnly?:***REMOVED***boolean;
}

export***REMOVED***const***REMOVED***MobileNavigation:***REMOVED***React.FC***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***navigate***REMOVED***=***REMOVED***useNavigate();
***REMOVED******REMOVED***const***REMOVED***location***REMOVED***=***REMOVED***useLocation();
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***user***REMOVED***}***REMOVED***=***REMOVED***useAuth();

***REMOVED******REMOVED***const***REMOVED***navItems:***REMOVED***NavItem[]***REMOVED***=***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Public***REMOVED***items***REMOVED***(always***REMOVED***visible)
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.HELP,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Aide',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<HelpCircle***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.ABOUT,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'À***REMOVED***propos',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<Info***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Auth***REMOVED***items***REMOVED***(only***REMOVED***when***REMOVED***not***REMOVED***authenticated)
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.AUTH.FAMILY,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Se***REMOVED***connecter',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<LogIn***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***publicOnly:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.AUTH.FAMILY,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Rejoindre',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<UserCheck***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***publicOnly:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Authenticated***REMOVED***items
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.ROOT,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Dashboard',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<Home***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.TREE,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Arbre',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<TreePine***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.MEMBERS,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Membres',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<Users***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.MEDIA,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Média',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<Play***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***ROUTES.DASHBOARD.INVITE,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***'Inviter',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***<UserPlus***REMOVED***className="w-4***REMOVED***h-4"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requiresAuth:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED***];

***REMOVED******REMOVED***const***REMOVED***isActiveRoute***REMOVED***=***REMOVED***(path:***REMOVED***string)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***location.pathname***REMOVED***===***REMOVED***path;
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***canShowItem***REMOVED***=***REMOVED***(item:***REMOVED***NavItem)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(item.requiresAuth***REMOVED***&&***REMOVED***!user)***REMOVED***return***REMOVED***false;
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(item.publicOnly***REMOVED***&&***REMOVED***user)***REMOVED***return***REMOVED***false;
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***true;
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***filteredNavItems***REMOVED***=***REMOVED***navItems.filter(canShowItem);

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="md:hidden***REMOVED***fixed***REMOVED***bottom-0***REMOVED***left-0***REMOVED***right-0***REMOVED***bg-white***REMOVED***border-t***REMOVED***border-gray-200***REMOVED***px-4***REMOVED***py-2***REMOVED***z-50">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex***REMOVED***justify-around***REMOVED***items-center***REMOVED***space-x-1">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{filteredNavItems.slice(0,***REMOVED***5).map((item)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={item.path}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant={isActiveRoute(item.path)***REMOVED***?***REMOVED***"default"***REMOVED***:***REMOVED***"ghost"}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size="sm"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={()***REMOVED***=>***REMOVED***navigate(item.path)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={`flex***REMOVED***flex-col***REMOVED***items-center***REMOVED***space-y-1***REMOVED***px-2***REMOVED***py-1***REMOVED***h-auto***REMOVED***min-w-0***REMOVED***${
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isActiveRoute(item.path)***REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***'bg-whatsapp-600***REMOVED***text-white'***REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***'text-gray-600***REMOVED***hover:text-whatsapp-600'
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}`}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{item.icon}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="text-xs***REMOVED***leading-none">{item.label}</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***);
};
