//***REMOVED***Types***REMOVED***harmonisés***REMOVED***pour***REMOVED***la***REMOVED***gestion***REMOVED***familiale
import***REMOVED***{***REMOVED***RelationshipType,***REMOVED***Civilite,***REMOVED***UserRole***REMOVED***}***REMOVED***from***REMOVED***'@/lib/validations/familySchema';

export***REMOVED***interface***REMOVED***FamilyMember***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***string;
***REMOVED******REMOVED***user_id:***REMOVED***string;
***REMOVED******REMOVED***first_name:***REMOVED***string;
***REMOVED******REMOVED***last_name:***REMOVED***string;
***REMOVED******REMOVED***email:***REMOVED***string;
***REMOVED******REMOVED***civilite:***REMOVED***Civilite;
***REMOVED******REMOVED***phone?:***REMOVED***string;
***REMOVED******REMOVED***profession?:***REMOVED***string;
***REMOVED******REMOVED***current_location?:***REMOVED***string;
***REMOVED******REMOVED***birth_place?:***REMOVED***string;
***REMOVED******REMOVED***birth_date?:***REMOVED***string;
***REMOVED******REMOVED***avatar_url?:***REMOVED***string;
***REMOVED******REMOVED***photo_url?:***REMOVED***string;
***REMOVED******REMOVED***relationship_type:***REMOVED***RelationshipType;
***REMOVED******REMOVED***father_id?:***REMOVED***string;
***REMOVED******REMOVED***mother_id?:***REMOVED***string;
***REMOVED******REMOVED***father_name?:***REMOVED***string;
***REMOVED******REMOVED***mother_name?:***REMOVED***string;
***REMOVED******REMOVED***spouse_name?:***REMOVED***string;
***REMOVED******REMOVED***is_admin:***REMOVED***boolean;
***REMOVED******REMOVED***is_patriarch:***REMOVED***boolean;
***REMOVED******REMOVED***is_parent:***REMOVED***boolean;
***REMOVED******REMOVED***situation?:***REMOVED***string;
***REMOVED******REMOVED***role:***REMOVED***UserRole;
***REMOVED******REMOVED***created_at:***REMOVED***string;
***REMOVED******REMOVED***updated_at:***REMOVED***string;
}

export***REMOVED***interface***REMOVED***FamilyTree***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***string;
***REMOVED******REMOVED***name:***REMOVED***string;
***REMOVED******REMOVED***description?:***REMOVED***string;
***REMOVED******REMOVED***created_by:***REMOVED***string;
***REMOVED******REMOVED***created_at:***REMOVED***string;
***REMOVED******REMOVED***updated_at:***REMOVED***string;
***REMOVED******REMOVED***members:***REMOVED***FamilyMember[];
}

export***REMOVED***interface***REMOVED***FamilyInvitation***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***string;
***REMOVED******REMOVED***email:***REMOVED***string;
***REMOVED******REMOVED***family_id:***REMOVED***string;
***REMOVED******REMOVED***invited_by:***REMOVED***string;
***REMOVED******REMOVED***status:***REMOVED***'pending'***REMOVED***|***REMOVED***'accepted'***REMOVED***|***REMOVED***'declined';
***REMOVED******REMOVED***created_at:***REMOVED***string;
***REMOVED******REMOVED***expires_at:***REMOVED***string;
}

export***REMOVED***interface***REMOVED***FamilyMessage***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***string;
***REMOVED******REMOVED***family_id:***REMOVED***string;
***REMOVED******REMOVED***sender_id:***REMOVED***string;
***REMOVED******REMOVED***content:***REMOVED***string;
***REMOVED******REMOVED***message_type:***REMOVED***'text'***REMOVED***|***REMOVED***'image'***REMOVED***|***REMOVED***'file';
***REMOVED******REMOVED***created_at:***REMOVED***string;
***REMOVED******REMOVED***sender:***REMOVED***FamilyMember;
}

export***REMOVED***interface***REMOVED***FamilyEvent***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***string;
***REMOVED******REMOVED***family_id:***REMOVED***string;
***REMOVED******REMOVED***title:***REMOVED***string;
***REMOVED******REMOVED***description?:***REMOVED***string;
***REMOVED******REMOVED***event_date:***REMOVED***string;
***REMOVED******REMOVED***event_type:***REMOVED***'birthday'***REMOVED***|***REMOVED***'anniversary'***REMOVED***|***REMOVED***'reunion'***REMOVED***|***REMOVED***'other';
***REMOVED******REMOVED***location?:***REMOVED***string;
***REMOVED******REMOVED***created_by:***REMOVED***string;
***REMOVED******REMOVED***created_at:***REMOVED***string;
***REMOVED******REMOVED***updated_at:***REMOVED***string;
}

//***REMOVED***Types***REMOVED***pour***REMOVED***les***REMOVED***formulaires
export***REMOVED***interface***REMOVED***CreateFamilyMemberData***REMOVED***{
***REMOVED******REMOVED***first_name:***REMOVED***string;
***REMOVED******REMOVED***last_name:***REMOVED***string;
***REMOVED******REMOVED***email:***REMOVED***string;
***REMOVED******REMOVED***civilite:***REMOVED***Civilite;
***REMOVED******REMOVED***phone?:***REMOVED***string;
***REMOVED******REMOVED***profession?:***REMOVED***string;
***REMOVED******REMOVED***current_location?:***REMOVED***string;
***REMOVED******REMOVED***birth_place?:***REMOVED***string;
***REMOVED******REMOVED***birth_date?:***REMOVED***string;
***REMOVED******REMOVED***relationship_type:***REMOVED***RelationshipType;
***REMOVED******REMOVED***father_id?:***REMOVED***string;
***REMOVED******REMOVED***mother_id?:***REMOVED***string;
***REMOVED******REMOVED***situation?:***REMOVED***string;
***REMOVED******REMOVED***role:***REMOVED***UserRole;
}

export***REMOVED***interface***REMOVED***UpdateFamilyMemberData***REMOVED***{
***REMOVED******REMOVED***first_name?:***REMOVED***string;
***REMOVED******REMOVED***last_name?:***REMOVED***string;
***REMOVED******REMOVED***phone?:***REMOVED***string;
***REMOVED******REMOVED***profession?:***REMOVED***string;
***REMOVED******REMOVED***current_location?:***REMOVED***string;
***REMOVED******REMOVED***birth_place?:***REMOVED***string;
***REMOVED******REMOVED***birth_date?:***REMOVED***string;
***REMOVED******REMOVED***relationship_type?:***REMOVED***RelationshipType;
***REMOVED******REMOVED***father_id?:***REMOVED***string;
***REMOVED******REMOVED***mother_id?:***REMOVED***string;
***REMOVED******REMOVED***situation?:***REMOVED***string;
***REMOVED******REMOVED***role?:***REMOVED***UserRole;
}

//***REMOVED***Types***REMOVED***pour***REMOVED***les***REMOVED***relations
export***REMOVED***interface***REMOVED***FamilyRelation***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***string;
***REMOVED******REMOVED***member_id:***REMOVED***string;
***REMOVED******REMOVED***related_member_id:***REMOVED***string;
***REMOVED******REMOVED***relation_type:***REMOVED***RelationshipType;
***REMOVED******REMOVED***created_at:***REMOVED***string;
}

//***REMOVED***Types***REMOVED***pour***REMOVED***les***REMOVED***statistiques
export***REMOVED***interface***REMOVED***FamilyStats***REMOVED***{
***REMOVED******REMOVED***total_members:***REMOVED***number;
***REMOVED******REMOVED***active_members:***REMOVED***number;
***REMOVED******REMOVED***pending_invitations:***REMOVED***number;
***REMOVED******REMOVED***upcoming_events:***REMOVED***number;
***REMOVED******REMOVED***recent_messages:***REMOVED***number;
}

//***REMOVED***Types***REMOVED***pour***REMOVED***les***REMOVED***notifications
export***REMOVED***interface***REMOVED***FamilyNotification***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***string;
***REMOVED******REMOVED***family_id:***REMOVED***string;
***REMOVED******REMOVED***user_id:***REMOVED***string;
***REMOVED******REMOVED***title:***REMOVED***string;
***REMOVED******REMOVED***message:***REMOVED***string;
***REMOVED******REMOVED***type:***REMOVED***'info'***REMOVED***|***REMOVED***'warning'***REMOVED***|***REMOVED***'success'***REMOVED***|***REMOVED***'error';
***REMOVED******REMOVED***read:***REMOVED***boolean;
***REMOVED******REMOVED***created_at:***REMOVED***string;
}
