
export***REMOVED***interface***REMOVED***ProfileData***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***string;
***REMOVED******REMOVED***user_id:***REMOVED***string;
***REMOVED******REMOVED***email:***REMOVED***string;
***REMOVED******REMOVED***first_name:***REMOVED***string;
***REMOVED******REMOVED***last_name:***REMOVED***string;
***REMOVED******REMOVED***phone?:***REMOVED***string;
***REMOVED******REMOVED***birth_date?:***REMOVED***string;
***REMOVED******REMOVED***birth_place?:***REMOVED***string;
***REMOVED******REMOVED***current_location?:***REMOVED***string;
***REMOVED******REMOVED***situation?:***REMOVED***string;
***REMOVED******REMOVED***profession?:***REMOVED***string;
***REMOVED******REMOVED***avatar_url?:***REMOVED***string;
***REMOVED******REMOVED***photo_url?:***REMOVED***string;
***REMOVED******REMOVED***title?:***REMOVED***'Patriarche'***REMOVED***|***REMOVED***'Matriarche'***REMOVED***|***REMOVED***'Père'***REMOVED***|***REMOVED***'Mère'***REMOVED***|***REMOVED***'Fils'***REMOVED***|***REMOVED***'Fille'***REMOVED***|***REMOVED***'Grand-père'***REMOVED***|***REMOVED***'Grand-mère'***REMOVED***|***REMOVED***'Petit-fils'***REMOVED***|***REMOVED***'Petite-fille'***REMOVED***|***REMOVED***'Oncle'***REMOVED***|***REMOVED***'Tante'***REMOVED***|***REMOVED***'Neveu'***REMOVED***|***REMOVED***'Nièce'***REMOVED***|***REMOVED***'Cousin'***REMOVED***|***REMOVED***'Cousine'***REMOVED***|***REMOVED***'Beau-père'***REMOVED***|***REMOVED***'Belle-mère'***REMOVED***|***REMOVED***'Beau-fils'***REMOVED***|***REMOVED***'Belle-fille'***REMOVED***|***REMOVED***'Frère'***REMOVED***|***REMOVED***'Sœur';
***REMOVED******REMOVED***relationship_type?:***REMOVED***'fils'***REMOVED***|***REMOVED***'fille'***REMOVED***|***REMOVED***'père'***REMOVED***|***REMOVED***'mère'***REMOVED***|***REMOVED***'cousin'***REMOVED***|***REMOVED***'cousine'***REMOVED***|***REMOVED***'tante'***REMOVED***|***REMOVED***'oncle'***REMOVED***|***REMOVED***'neveu'***REMOVED***|***REMOVED***'nièce'***REMOVED***|***REMOVED***'petit-fils'***REMOVED***|***REMOVED***'petite-fille'***REMOVED***|***REMOVED***'grand-père'***REMOVED***|***REMOVED***'grande-mère'***REMOVED***|***REMOVED***'époux'***REMOVED***|***REMOVED***'épouse'***REMOVED***|***REMOVED***'patriarche'***REMOVED***|***REMOVED***'matriarche'***REMOVED***|***REMOVED***'conjoint';
***REMOVED******REMOVED***father_name?:***REMOVED***string;
***REMOVED******REMOVED***mother_name?:***REMOVED***string;
***REMOVED******REMOVED***spouse_name?:***REMOVED***string;
***REMOVED******REMOVED***is_admin?:***REMOVED***boolean;
***REMOVED******REMOVED***is_parent?:***REMOVED***boolean;
***REMOVED******REMOVED***is_patriarch?:***REMOVED***boolean;
***REMOVED******REMOVED***created_at?:***REMOVED***string;
***REMOVED******REMOVED***updated_at?:***REMOVED***string;
}
