import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED***{***REMOVED***Slot***REMOVED***}***REMOVED***from***REMOVED***"@radix-ui/react-slot"
import***REMOVED***{***REMOVED***ChevronRight,***REMOVED***MoreHorizontal***REMOVED***}***REMOVED***from***REMOVED***"lucide-react"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"

const***REMOVED***Breadcrumb***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLElement,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<"nav">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***separator?:***REMOVED***React.ReactNode
***REMOVED******REMOVED***}
>(({***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***<nav***REMOVED***ref={ref}***REMOVED***aria-label="breadcrumb"***REMOVED***{...props}***REMOVED***/>)
Breadcrumb.displayName***REMOVED***=***REMOVED***"Breadcrumb"

const***REMOVED***BreadcrumbList***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLOListElement,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<"ol">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<ol
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***flex-wrap***REMOVED***items-center***REMOVED***gap-1.5***REMOVED***break-words***REMOVED***text-sm***REMOVED***text-muted-foreground***REMOVED***sm:gap-2.5",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
BreadcrumbList.displayName***REMOVED***=***REMOVED***"BreadcrumbList"

const***REMOVED***BreadcrumbItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLLIElement,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<"li">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<li
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("inline-flex***REMOVED***items-center***REMOVED***gap-1.5",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
BreadcrumbItem.displayName***REMOVED***=***REMOVED***"BreadcrumbItem"

const***REMOVED***BreadcrumbLink***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLAnchorElement,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<"a">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***asChild?:***REMOVED***boolean
***REMOVED******REMOVED***}
>(({***REMOVED***asChild,***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***Comp***REMOVED***=***REMOVED***asChild***REMOVED***?***REMOVED***Slot***REMOVED***:***REMOVED***"a"

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Comp
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("transition-colors***REMOVED***hover:text-foreground",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
BreadcrumbLink.displayName***REMOVED***=***REMOVED***"BreadcrumbLink"

const***REMOVED***BreadcrumbPage***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLSpanElement,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<"span">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<span
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***role="link"
***REMOVED******REMOVED******REMOVED******REMOVED***aria-disabled="true"
***REMOVED******REMOVED******REMOVED******REMOVED***aria-current="page"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("font-normal***REMOVED***text-foreground",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
BreadcrumbPage.displayName***REMOVED***=***REMOVED***"BreadcrumbPage"

const***REMOVED***BreadcrumbSeparator***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***children,
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<"li">)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<li
***REMOVED******REMOVED******REMOVED******REMOVED***role="presentation"
***REMOVED******REMOVED******REMOVED******REMOVED***aria-hidden="true"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("[&>svg]:size-3.5",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***{children***REMOVED***??***REMOVED***<ChevronRight***REMOVED***/>}
***REMOVED******REMOVED***</li>
)
BreadcrumbSeparator.displayName***REMOVED***=***REMOVED***"BreadcrumbSeparator"

const***REMOVED***BreadcrumbEllipsis***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<"span">)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<span
***REMOVED******REMOVED******REMOVED******REMOVED***role="presentation"
***REMOVED******REMOVED******REMOVED******REMOVED***aria-hidden="true"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("flex***REMOVED***h-9***REMOVED***w-9***REMOVED***items-center***REMOVED***justify-center",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<MoreHorizontal***REMOVED***className="h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="sr-only">More</span>
***REMOVED******REMOVED***</span>
)
BreadcrumbEllipsis.displayName***REMOVED***=***REMOVED***"BreadcrumbElipssis"

export***REMOVED***{
***REMOVED******REMOVED***Breadcrumb,
***REMOVED******REMOVED***BreadcrumbList,
***REMOVED******REMOVED***BreadcrumbItem,
***REMOVED******REMOVED***BreadcrumbLink,
***REMOVED******REMOVED***BreadcrumbPage,
***REMOVED******REMOVED***BreadcrumbSeparator,
***REMOVED******REMOVED***BreadcrumbEllipsis,
}
