import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED*******REMOVED***as***REMOVED***RechartsPrimitive***REMOVED***from***REMOVED***"recharts"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"

//***REMOVED***Format:***REMOVED***{***REMOVED***THEME_NAME:***REMOVED***CSS_SELECTOR***REMOVED***}
const***REMOVED***THEMES***REMOVED***=***REMOVED***{***REMOVED***light:***REMOVED***"",***REMOVED***dark:***REMOVED***".dark"***REMOVED***}***REMOVED***as***REMOVED***const

export***REMOVED***type***REMOVED***ChartConfig***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***[k***REMOVED***in***REMOVED***string]:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***label?:***REMOVED***React.ReactNode
***REMOVED******REMOVED******REMOVED******REMOVED***icon?:***REMOVED***React.ComponentType
***REMOVED******REMOVED***}***REMOVED***&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***|***REMOVED***{***REMOVED***color?:***REMOVED***string;***REMOVED***theme?:***REMOVED***never***REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***|***REMOVED***{***REMOVED***color?:***REMOVED***never;***REMOVED***theme:***REMOVED***Record<keyof***REMOVED***typeof***REMOVED***THEMES,***REMOVED***string>***REMOVED***}
***REMOVED******REMOVED***)
}

type***REMOVED***ChartContextProps***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***config:***REMOVED***ChartConfig
}

const***REMOVED***ChartContext***REMOVED***=***REMOVED***React.createContext<ChartContextProps***REMOVED***|***REMOVED***null>(null)

function***REMOVED***useChart()***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***context***REMOVED***=***REMOVED***React.useContext(ChartContext)

***REMOVED******REMOVED***if***REMOVED***(!context)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***new***REMOVED***Error("useChart***REMOVED***must***REMOVED***be***REMOVED***used***REMOVED***within***REMOVED***a***REMOVED***<ChartContainer***REMOVED***/>")
***REMOVED******REMOVED***}

***REMOVED******REMOVED***return***REMOVED***context
}

const***REMOVED***ChartContainer***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***config:***REMOVED***ChartConfig
***REMOVED******REMOVED******REMOVED******REMOVED***children:***REMOVED***React.ComponentProps<
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***typeof***REMOVED***RechartsPrimitive.ResponsiveContainer
***REMOVED******REMOVED******REMOVED******REMOVED***>["children"]
***REMOVED******REMOVED***}
>(({***REMOVED***id,***REMOVED***className,***REMOVED***children,***REMOVED***config,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***uniqueId***REMOVED***=***REMOVED***React.useId()
***REMOVED******REMOVED***const***REMOVED***chartId***REMOVED***=***REMOVED***`chart-${id***REMOVED***||***REMOVED***uniqueId.replace(/:/g,***REMOVED***"")}`

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<ChartContext.Provider***REMOVED***value={{***REMOVED***config***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-chart={chartId}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***aspect-video***REMOVED***justify-center***REMOVED***text-xs***REMOVED***[&_.recharts-cartesian-axis-tick_text]:fill-muted-foreground***REMOVED***[&_.recharts-cartesian-grid_line[stroke='#ccc']]:stroke-border/50***REMOVED***[&_.recharts-curve.recharts-tooltip-cursor]:stroke-border***REMOVED***[&_.recharts-dot[stroke='#fff']]:stroke-transparent***REMOVED***[&_.recharts-layer]:outline-none***REMOVED***[&_.recharts-polar-grid_[stroke='#ccc']]:stroke-border***REMOVED***[&_.recharts-radial-bar-background-sector]:fill-muted***REMOVED***[&_.recharts-rectangle.recharts-tooltip-cursor]:fill-muted***REMOVED***[&_.recharts-reference-line_[stroke='#ccc']]:stroke-border***REMOVED***[&_.recharts-sector[stroke='#fff']]:stroke-transparent***REMOVED***[&_.recharts-sector]:outline-none***REMOVED***[&_.recharts-surface]:outline-none",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ChartStyle***REMOVED***id={chartId}***REMOVED***config={config}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<RechartsPrimitive.ResponsiveContainer>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</RechartsPrimitive.ResponsiveContainer>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED***</ChartContext.Provider>
***REMOVED******REMOVED***)
})
ChartContainer.displayName***REMOVED***=***REMOVED***"Chart"

const***REMOVED***ChartStyle***REMOVED***=***REMOVED***({***REMOVED***id,***REMOVED***config***REMOVED***}:***REMOVED***{***REMOVED***id:***REMOVED***string;***REMOVED***config:***REMOVED***ChartConfig***REMOVED***})***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***colorConfig***REMOVED***=***REMOVED***Object.entries(config).filter(
***REMOVED******REMOVED******REMOVED******REMOVED***([_,***REMOVED***config])***REMOVED***=>***REMOVED***config.theme***REMOVED***||***REMOVED***config.color
***REMOVED******REMOVED***)

***REMOVED******REMOVED***if***REMOVED***(!colorConfig.length)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***null
***REMOVED******REMOVED***}

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<style
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***dangerouslySetInnerHTML={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***__html:***REMOVED***Object.entries(THEMES)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***.map(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***([theme,***REMOVED***prefix])***REMOVED***=>***REMOVED***`
${prefix}***REMOVED***[data-chart=${id}]***REMOVED***{
${colorConfig
***REMOVED******REMOVED***.map(([key,***REMOVED***itemConfig])***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***color***REMOVED***=
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***itemConfig.theme?.[theme***REMOVED***as***REMOVED***keyof***REMOVED***typeof***REMOVED***itemConfig.theme]***REMOVED***||
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***itemConfig.color
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***color***REMOVED***?***REMOVED***`***REMOVED******REMOVED***--color-${key}:***REMOVED***${color};`***REMOVED***:***REMOVED***null
***REMOVED******REMOVED***})
***REMOVED******REMOVED***.join("\n")}
}
`
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***.join("\n"),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

const***REMOVED***ChartTooltip***REMOVED***=***REMOVED***RechartsPrimitive.Tooltip

const***REMOVED***ChartTooltipContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<typeof***REMOVED***RechartsPrimitive.Tooltip>***REMOVED***&
***REMOVED******REMOVED******REMOVED******REMOVED***React.ComponentProps<"div">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hideLabel?:***REMOVED***boolean
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hideIndicator?:***REMOVED***boolean
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***indicator?:***REMOVED***"line"***REMOVED***|***REMOVED***"dot"***REMOVED***|***REMOVED***"dashed"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***nameKey?:***REMOVED***string
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***labelKey?:***REMOVED***string
***REMOVED******REMOVED******REMOVED******REMOVED***}
>(
***REMOVED******REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***active,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***payload,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***indicator***REMOVED***=***REMOVED***"dot",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hideLabel***REMOVED***=***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hideIndicator***REMOVED***=***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***labelFormatter,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***labelClassName,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***formatter,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***color,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***nameKey,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***labelKey,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***ref
***REMOVED******REMOVED***)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***config***REMOVED***}***REMOVED***=***REMOVED***useChart()

***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***tooltipLabel***REMOVED***=***REMOVED***React.useMemo(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(hideLabel***REMOVED***||***REMOVED***!payload?.length)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***null
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***[item]***REMOVED***=***REMOVED***payload
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***key***REMOVED***=***REMOVED***`${labelKey***REMOVED***||***REMOVED***item.dataKey***REMOVED***||***REMOVED***item.name***REMOVED***||***REMOVED***"value"}`
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***itemConfig***REMOVED***=***REMOVED***getPayloadConfigFromPayload(config,***REMOVED***item,***REMOVED***key)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***value***REMOVED***=
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***!labelKey***REMOVED***&&***REMOVED***typeof***REMOVED***label***REMOVED***===***REMOVED***"string"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***config[label***REMOVED***as***REMOVED***keyof***REMOVED***typeof***REMOVED***config]?.label***REMOVED***||***REMOVED***label
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***itemConfig?.label

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(labelFormatter)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className={cn("font-medium",***REMOVED***labelClassName)}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{labelFormatter(value,***REMOVED***payload)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!value)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***null
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***<div***REMOVED***className={cn("font-medium",***REMOVED***labelClassName)}>{value}</div>
***REMOVED******REMOVED******REMOVED******REMOVED***},***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***labelFormatter,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***payload,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hideLabel,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***labelClassName,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***config,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***labelKey,
***REMOVED******REMOVED******REMOVED******REMOVED***])

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!active***REMOVED***||***REMOVED***!payload?.length)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***null
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***nestLabel***REMOVED***=***REMOVED***payload.length***REMOVED***===***REMOVED***1***REMOVED***&&***REMOVED***indicator***REMOVED***!==***REMOVED***"dot"

***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"grid***REMOVED***min-w-[8rem]***REMOVED***items-start***REMOVED***gap-1.5***REMOVED***rounded-lg***REMOVED***border***REMOVED***border-border/50***REMOVED***bg-background***REMOVED***px-2.5***REMOVED***py-1.5***REMOVED***text-xs***REMOVED***shadow-xl",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{!nestLabel***REMOVED***?***REMOVED***tooltipLabel***REMOVED***:***REMOVED***null}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="grid***REMOVED***gap-1.5">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{payload.map((item,***REMOVED***index)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***key***REMOVED***=***REMOVED***`${nameKey***REMOVED***||***REMOVED***item.name***REMOVED***||***REMOVED***item.dataKey***REMOVED***||***REMOVED***"value"}`
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***itemConfig***REMOVED***=***REMOVED***getPayloadConfigFromPayload(config,***REMOVED***item,***REMOVED***key)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***indicatorColor***REMOVED***=***REMOVED***color***REMOVED***||***REMOVED***item.payload.fill***REMOVED***||***REMOVED***item.color

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={item.dataKey}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***w-full***REMOVED***flex-wrap***REMOVED***items-stretch***REMOVED***gap-2***REMOVED***[&>svg]:h-2.5***REMOVED***[&>svg]:w-2.5***REMOVED***[&>svg]:text-muted-foreground",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***indicator***REMOVED***===***REMOVED***"dot"***REMOVED***&&***REMOVED***"items-center"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{formatter***REMOVED***&&***REMOVED***item?.value***REMOVED***!==***REMOVED***undefined***REMOVED***&&***REMOVED***item.name***REMOVED***?***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***formatter(item.value,***REMOVED***item.name,***REMOVED***item,***REMOVED***index,***REMOVED***item.payload)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***:***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{itemConfig?.icon***REMOVED***?***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<itemConfig.icon***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***:***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***!hideIndicator***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"shrink-0***REMOVED***rounded-[2px]***REMOVED***border-[--color-border]***REMOVED***bg-[--color-bg]",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"h-2.5***REMOVED***w-2.5":***REMOVED***indicator***REMOVED***===***REMOVED***"dot",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"w-1":***REMOVED***indicator***REMOVED***===***REMOVED***"line",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"w-0***REMOVED***border-[1.5px]***REMOVED***border-dashed***REMOVED***bg-transparent":
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***indicator***REMOVED***===***REMOVED***"dashed",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"my-0.5":***REMOVED***nestLabel***REMOVED***&&***REMOVED***indicator***REMOVED***===***REMOVED***"dashed",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***style={
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"--color-bg":***REMOVED***indicatorColor,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"--color-border":***REMOVED***indicatorColor,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***as***REMOVED***React.CSSProperties
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***flex-1***REMOVED***justify-between***REMOVED***leading-none",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***nestLabel***REMOVED***?***REMOVED***"items-end"***REMOVED***:***REMOVED***"items-center"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="grid***REMOVED***gap-1.5">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{nestLabel***REMOVED***?***REMOVED***tooltipLabel***REMOVED***:***REMOVED***null}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="text-muted-foreground">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{itemConfig?.label***REMOVED***||***REMOVED***item.name}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{item.value***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="font-mono***REMOVED***font-medium***REMOVED***tabular-nums***REMOVED***text-foreground">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{item.value.toLocaleString()}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***})}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED***}
)
ChartTooltipContent.displayName***REMOVED***=***REMOVED***"ChartTooltip"

const***REMOVED***ChartLegend***REMOVED***=***REMOVED***RechartsPrimitive.Legend

const***REMOVED***ChartLegendContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">***REMOVED***&
***REMOVED******REMOVED******REMOVED******REMOVED***Pick<RechartsPrimitive.LegendProps,***REMOVED***"payload"***REMOVED***|***REMOVED***"verticalAlign">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hideIcon?:***REMOVED***boolean
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***nameKey?:***REMOVED***string
***REMOVED******REMOVED******REMOVED******REMOVED***}
>(
***REMOVED******REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***className,***REMOVED***hideIcon***REMOVED***=***REMOVED***false,***REMOVED***payload,***REMOVED***verticalAlign***REMOVED***=***REMOVED***"bottom",***REMOVED***nameKey***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***ref
***REMOVED******REMOVED***)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***config***REMOVED***}***REMOVED***=***REMOVED***useChart()

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!payload?.length)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***null
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***items-center***REMOVED***justify-center***REMOVED***gap-4",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***verticalAlign***REMOVED***===***REMOVED***"top"***REMOVED***?***REMOVED***"pb-3"***REMOVED***:***REMOVED***"pt-3",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{payload.map((item)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***key***REMOVED***=***REMOVED***`${nameKey***REMOVED***||***REMOVED***item.dataKey***REMOVED***||***REMOVED***"value"}`
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***itemConfig***REMOVED***=***REMOVED***getPayloadConfigFromPayload(config,***REMOVED***item,***REMOVED***key)

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={item.value}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***items-center***REMOVED***gap-1.5***REMOVED***[&>svg]:h-3***REMOVED***[&>svg]:w-3***REMOVED***[&>svg]:text-muted-foreground"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{itemConfig?.icon***REMOVED***&&***REMOVED***!hideIcon***REMOVED***?***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<itemConfig.icon***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***:***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="h-2***REMOVED***w-2***REMOVED***shrink-0***REMOVED***rounded-[2px]"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***style={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***backgroundColor:***REMOVED***item.color,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{itemConfig?.label}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***})}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED***}
)
ChartLegendContent.displayName***REMOVED***=***REMOVED***"ChartLegend"

//***REMOVED***Helper***REMOVED***to***REMOVED***extract***REMOVED***item***REMOVED***config***REMOVED***from***REMOVED***a***REMOVED***payload.
function***REMOVED***getPayloadConfigFromPayload(
***REMOVED******REMOVED***config:***REMOVED***ChartConfig,
***REMOVED******REMOVED***payload:***REMOVED***unknown,
***REMOVED******REMOVED***key:***REMOVED***string
)***REMOVED***{
***REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***payload***REMOVED***!==***REMOVED***"object"***REMOVED***||***REMOVED***payload***REMOVED***===***REMOVED***null)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***undefined
***REMOVED******REMOVED***}

***REMOVED******REMOVED***const***REMOVED***payloadPayload***REMOVED***=
***REMOVED******REMOVED******REMOVED******REMOVED***"payload"***REMOVED***in***REMOVED***payload***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED***typeof***REMOVED***payload.payload***REMOVED***===***REMOVED***"object"***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED***payload.payload***REMOVED***!==***REMOVED***null
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***payload.payload
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***undefined

***REMOVED******REMOVED***let***REMOVED***configLabelKey:***REMOVED***string***REMOVED***=***REMOVED***key

***REMOVED******REMOVED***if***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***key***REMOVED***in***REMOVED***payload***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED***typeof***REMOVED***payload[key***REMOVED***as***REMOVED***keyof***REMOVED***typeof***REMOVED***payload]***REMOVED***===***REMOVED***"string"
***REMOVED******REMOVED***)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***configLabelKey***REMOVED***=***REMOVED***payload[key***REMOVED***as***REMOVED***keyof***REMOVED***typeof***REMOVED***payload]***REMOVED***as***REMOVED***string
***REMOVED******REMOVED***}***REMOVED***else***REMOVED***if***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***payloadPayload***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED***key***REMOVED***in***REMOVED***payloadPayload***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED***typeof***REMOVED***payloadPayload[key***REMOVED***as***REMOVED***keyof***REMOVED***typeof***REMOVED***payloadPayload]***REMOVED***===***REMOVED***"string"
***REMOVED******REMOVED***)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***configLabelKey***REMOVED***=***REMOVED***payloadPayload[
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key***REMOVED***as***REMOVED***keyof***REMOVED***typeof***REMOVED***payloadPayload
***REMOVED******REMOVED******REMOVED******REMOVED***]***REMOVED***as***REMOVED***string
***REMOVED******REMOVED***}

***REMOVED******REMOVED***return***REMOVED***configLabelKey***REMOVED***in***REMOVED***config
***REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***config[configLabelKey]
***REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***config[key***REMOVED***as***REMOVED***keyof***REMOVED***typeof***REMOVED***config]
}

export***REMOVED***{
***REMOVED******REMOVED***ChartContainer,
***REMOVED******REMOVED***ChartTooltip,
***REMOVED******REMOVED***ChartTooltipContent,
***REMOVED******REMOVED***ChartLegend,
***REMOVED******REMOVED***ChartLegendContent,
***REMOVED******REMOVED***ChartStyle,
}
