import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED*******REMOVED***as***REMOVED***DropdownMenuPrimitive***REMOVED***from***REMOVED***"@radix-ui/react-dropdown-menu"
import***REMOVED***{***REMOVED***Check,***REMOVED***ChevronRight,***REMOVED***Circle***REMOVED***}***REMOVED***from***REMOVED***"lucide-react"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"

const***REMOVED***DropdownMenu***REMOVED***=***REMOVED***DropdownMenuPrimitive.Root

const***REMOVED***DropdownMenuTrigger***REMOVED***=***REMOVED***DropdownMenuPrimitive.Trigger

const***REMOVED***DropdownMenuGroup***REMOVED***=***REMOVED***DropdownMenuPrimitive.Group

const***REMOVED***DropdownMenuPortal***REMOVED***=***REMOVED***DropdownMenuPrimitive.Portal

const***REMOVED***DropdownMenuSub***REMOVED***=***REMOVED***DropdownMenuPrimitive.Sub

const***REMOVED***DropdownMenuRadioGroup***REMOVED***=***REMOVED***DropdownMenuPrimitive.RadioGroup

const***REMOVED***DropdownMenuSubTrigger***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***DropdownMenuPrimitive.SubTrigger>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***DropdownMenuPrimitive.SubTrigger>***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***inset?:***REMOVED***boolean
***REMOVED******REMOVED***}
>(({***REMOVED***className,***REMOVED***inset,***REMOVED***children,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<DropdownMenuPrimitive.SubTrigger
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***cursor-default***REMOVED***select-none***REMOVED***items-center***REMOVED***rounded-sm***REMOVED***px-2***REMOVED***py-1.5***REMOVED***text-sm***REMOVED***outline-none***REMOVED***focus:bg-accent***REMOVED***data-[state=open]:bg-accent",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***inset***REMOVED***&&***REMOVED***"pl-8",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED***<ChevronRight***REMOVED***className="ml-auto***REMOVED***h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED***</DropdownMenuPrimitive.SubTrigger>
))
DropdownMenuSubTrigger.displayName***REMOVED***=
***REMOVED******REMOVED***DropdownMenuPrimitive.SubTrigger.displayName

const***REMOVED***DropdownMenuSubContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***DropdownMenuPrimitive.SubContent>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***DropdownMenuPrimitive.SubContent>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<DropdownMenuPrimitive.SubContent
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"z-50***REMOVED***min-w-[8rem]***REMOVED***overflow-hidden***REMOVED***rounded-md***REMOVED***border***REMOVED***bg-popover***REMOVED***p-1***REMOVED***text-popover-foreground***REMOVED***shadow-lg***REMOVED***data-[state=open]:animate-in***REMOVED***data-[state=closed]:animate-out***REMOVED***data-[state=closed]:fade-out-0***REMOVED***data-[state=open]:fade-in-0***REMOVED***data-[state=closed]:zoom-out-95***REMOVED***data-[state=open]:zoom-in-95***REMOVED***data-[side=bottom]:slide-in-from-top-2***REMOVED***data-[side=left]:slide-in-from-right-2***REMOVED***data-[side=right]:slide-in-from-left-2***REMOVED***data-[side=top]:slide-in-from-bottom-2",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
DropdownMenuSubContent.displayName***REMOVED***=
***REMOVED******REMOVED***DropdownMenuPrimitive.SubContent.displayName

const***REMOVED***DropdownMenuContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***DropdownMenuPrimitive.Content>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***DropdownMenuPrimitive.Content>
>(({***REMOVED***className,***REMOVED***sideOffset***REMOVED***=***REMOVED***4,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<DropdownMenuPrimitive.Portal>
***REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenuPrimitive.Content
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sideOffset={sideOffset}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"z-50***REMOVED***min-w-[8rem]***REMOVED***overflow-hidden***REMOVED***rounded-md***REMOVED***border***REMOVED***bg-popover***REMOVED***p-1***REMOVED***text-popover-foreground***REMOVED***shadow-md***REMOVED***data-[state=open]:animate-in***REMOVED***data-[state=closed]:animate-out***REMOVED***data-[state=closed]:fade-out-0***REMOVED***data-[state=open]:fade-in-0***REMOVED***data-[state=closed]:zoom-out-95***REMOVED***data-[state=open]:zoom-in-95***REMOVED***data-[side=bottom]:slide-in-from-top-2***REMOVED***data-[side=left]:slide-in-from-right-2***REMOVED***data-[side=right]:slide-in-from-left-2***REMOVED***data-[side=top]:slide-in-from-bottom-2",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***</DropdownMenuPrimitive.Portal>
))
DropdownMenuContent.displayName***REMOVED***=***REMOVED***DropdownMenuPrimitive.Content.displayName

const***REMOVED***DropdownMenuItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***DropdownMenuPrimitive.Item>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***DropdownMenuPrimitive.Item>***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***inset?:***REMOVED***boolean
***REMOVED******REMOVED***}
>(({***REMOVED***className,***REMOVED***inset,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<DropdownMenuPrimitive.Item
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"relative***REMOVED***flex***REMOVED***cursor-default***REMOVED***select-none***REMOVED***items-center***REMOVED***rounded-sm***REMOVED***px-2***REMOVED***py-1.5***REMOVED***text-sm***REMOVED***outline-none***REMOVED***transition-colors***REMOVED***focus:bg-accent***REMOVED***focus:text-accent-foreground***REMOVED***data-[disabled]:pointer-events-none***REMOVED***data-[disabled]:opacity-50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***inset***REMOVED***&&***REMOVED***"pl-8",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
DropdownMenuItem.displayName***REMOVED***=***REMOVED***DropdownMenuPrimitive.Item.displayName

const***REMOVED***DropdownMenuCheckboxItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***DropdownMenuPrimitive.CheckboxItem>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***DropdownMenuPrimitive.CheckboxItem>
>(({***REMOVED***className,***REMOVED***children,***REMOVED***checked,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<DropdownMenuPrimitive.CheckboxItem
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"relative***REMOVED***flex***REMOVED***cursor-default***REMOVED***select-none***REMOVED***items-center***REMOVED***rounded-sm***REMOVED***py-1.5***REMOVED***pl-8***REMOVED***pr-2***REMOVED***text-sm***REMOVED***outline-none***REMOVED***transition-colors***REMOVED***focus:bg-accent***REMOVED***focus:text-accent-foreground***REMOVED***data-[disabled]:pointer-events-none***REMOVED***data-[disabled]:opacity-50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***checked={checked}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="absolute***REMOVED***left-2***REMOVED***flex***REMOVED***h-3.5***REMOVED***w-3.5***REMOVED***items-center***REMOVED***justify-center">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenuPrimitive.ItemIndicator>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Check***REMOVED***className="h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DropdownMenuPrimitive.ItemIndicator>
***REMOVED******REMOVED******REMOVED******REMOVED***</span>
***REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED***</DropdownMenuPrimitive.CheckboxItem>
))
DropdownMenuCheckboxItem.displayName***REMOVED***=
***REMOVED******REMOVED***DropdownMenuPrimitive.CheckboxItem.displayName

const***REMOVED***DropdownMenuRadioItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***DropdownMenuPrimitive.RadioItem>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***DropdownMenuPrimitive.RadioItem>
>(({***REMOVED***className,***REMOVED***children,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<DropdownMenuPrimitive.RadioItem
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"relative***REMOVED***flex***REMOVED***cursor-default***REMOVED***select-none***REMOVED***items-center***REMOVED***rounded-sm***REMOVED***py-1.5***REMOVED***pl-8***REMOVED***pr-2***REMOVED***text-sm***REMOVED***outline-none***REMOVED***transition-colors***REMOVED***focus:bg-accent***REMOVED***focus:text-accent-foreground***REMOVED***data-[disabled]:pointer-events-none***REMOVED***data-[disabled]:opacity-50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="absolute***REMOVED***left-2***REMOVED***flex***REMOVED***h-3.5***REMOVED***w-3.5***REMOVED***items-center***REMOVED***justify-center">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenuPrimitive.ItemIndicator>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Circle***REMOVED***className="h-2***REMOVED***w-2***REMOVED***fill-current"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DropdownMenuPrimitive.ItemIndicator>
***REMOVED******REMOVED******REMOVED******REMOVED***</span>
***REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED***</DropdownMenuPrimitive.RadioItem>
))
DropdownMenuRadioItem.displayName***REMOVED***=***REMOVED***DropdownMenuPrimitive.RadioItem.displayName

const***REMOVED***DropdownMenuLabel***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***DropdownMenuPrimitive.Label>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***DropdownMenuPrimitive.Label>***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***inset?:***REMOVED***boolean
***REMOVED******REMOVED***}
>(({***REMOVED***className,***REMOVED***inset,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<DropdownMenuPrimitive.Label
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"px-2***REMOVED***py-1.5***REMOVED***text-sm***REMOVED***font-semibold",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***inset***REMOVED***&&***REMOVED***"pl-8",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
DropdownMenuLabel.displayName***REMOVED***=***REMOVED***DropdownMenuPrimitive.Label.displayName

const***REMOVED***DropdownMenuSeparator***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***DropdownMenuPrimitive.Separator>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***DropdownMenuPrimitive.Separator>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<DropdownMenuPrimitive.Separator
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("-mx-1***REMOVED***my-1***REMOVED***h-px***REMOVED***bg-muted",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
DropdownMenuSeparator.displayName***REMOVED***=***REMOVED***DropdownMenuPrimitive.Separator.displayName

const***REMOVED***DropdownMenuShortcut***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.HTMLAttributes<HTMLSpanElement>)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<span
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("ml-auto***REMOVED***text-xs***REMOVED***tracking-widest***REMOVED***opacity-60",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}
DropdownMenuShortcut.displayName***REMOVED***=***REMOVED***"DropdownMenuShortcut"

export***REMOVED***{
***REMOVED******REMOVED***DropdownMenu,
***REMOVED******REMOVED***DropdownMenuTrigger,
***REMOVED******REMOVED***DropdownMenuContent,
***REMOVED******REMOVED***DropdownMenuItem,
***REMOVED******REMOVED***DropdownMenuCheckboxItem,
***REMOVED******REMOVED***DropdownMenuRadioItem,
***REMOVED******REMOVED***DropdownMenuLabel,
***REMOVED******REMOVED***DropdownMenuSeparator,
***REMOVED******REMOVED***DropdownMenuShortcut,
***REMOVED******REMOVED***DropdownMenuGroup,
***REMOVED******REMOVED***DropdownMenuPortal,
***REMOVED******REMOVED***DropdownMenuSub,
***REMOVED******REMOVED***DropdownMenuSubContent,
***REMOVED******REMOVED***DropdownMenuSubTrigger,
***REMOVED******REMOVED***DropdownMenuRadioGroup,
}
