import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED*******REMOVED***as***REMOVED***MenubarPrimitive***REMOVED***from***REMOVED***"@radix-ui/react-menubar"
import***REMOVED***{***REMOVED***Check,***REMOVED***ChevronRight,***REMOVED***Circle***REMOVED***}***REMOVED***from***REMOVED***"lucide-react"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"

const***REMOVED***MenubarMenu***REMOVED***=***REMOVED***MenubarPrimitive.Menu

const***REMOVED***MenubarGroup***REMOVED***=***REMOVED***MenubarPrimitive.Group

const***REMOVED***MenubarPortal***REMOVED***=***REMOVED***MenubarPrimitive.Portal

const***REMOVED***MenubarSub***REMOVED***=***REMOVED***MenubarPrimitive.Sub

const***REMOVED***MenubarRadioGroup***REMOVED***=***REMOVED***MenubarPrimitive.RadioGroup

const***REMOVED***Menubar***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***MenubarPrimitive.Root>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***MenubarPrimitive.Root>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<MenubarPrimitive.Root
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***h-10***REMOVED***items-center***REMOVED***space-x-1***REMOVED***rounded-md***REMOVED***border***REMOVED***bg-background***REMOVED***p-1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
Menubar.displayName***REMOVED***=***REMOVED***MenubarPrimitive.Root.displayName

const***REMOVED***MenubarTrigger***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***MenubarPrimitive.Trigger>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***MenubarPrimitive.Trigger>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<MenubarPrimitive.Trigger
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***cursor-default***REMOVED***select-none***REMOVED***items-center***REMOVED***rounded-sm***REMOVED***px-3***REMOVED***py-1.5***REMOVED***text-sm***REMOVED***font-medium***REMOVED***outline-none***REMOVED***focus:bg-accent***REMOVED***focus:text-accent-foreground***REMOVED***data-[state=open]:bg-accent***REMOVED***data-[state=open]:text-accent-foreground",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
MenubarTrigger.displayName***REMOVED***=***REMOVED***MenubarPrimitive.Trigger.displayName

const***REMOVED***MenubarSubTrigger***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***MenubarPrimitive.SubTrigger>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***MenubarPrimitive.SubTrigger>***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***inset?:***REMOVED***boolean
***REMOVED******REMOVED***}
>(({***REMOVED***className,***REMOVED***inset,***REMOVED***children,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<MenubarPrimitive.SubTrigger
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***cursor-default***REMOVED***select-none***REMOVED***items-center***REMOVED***rounded-sm***REMOVED***px-2***REMOVED***py-1.5***REMOVED***text-sm***REMOVED***outline-none***REMOVED***focus:bg-accent***REMOVED***focus:text-accent-foreground***REMOVED***data-[state=open]:bg-accent***REMOVED***data-[state=open]:text-accent-foreground",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***inset***REMOVED***&&***REMOVED***"pl-8",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED***<ChevronRight***REMOVED***className="ml-auto***REMOVED***h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED***</MenubarPrimitive.SubTrigger>
))
MenubarSubTrigger.displayName***REMOVED***=***REMOVED***MenubarPrimitive.SubTrigger.displayName

const***REMOVED***MenubarSubContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***MenubarPrimitive.SubContent>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***MenubarPrimitive.SubContent>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<MenubarPrimitive.SubContent
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"z-50***REMOVED***min-w-[8rem]***REMOVED***overflow-hidden***REMOVED***rounded-md***REMOVED***border***REMOVED***bg-popover***REMOVED***p-1***REMOVED***text-popover-foreground***REMOVED***data-[state=open]:animate-in***REMOVED***data-[state=closed]:animate-out***REMOVED***data-[state=closed]:fade-out-0***REMOVED***data-[state=open]:fade-in-0***REMOVED***data-[state=closed]:zoom-out-95***REMOVED***data-[state=open]:zoom-in-95***REMOVED***data-[side=bottom]:slide-in-from-top-2***REMOVED***data-[side=left]:slide-in-from-right-2***REMOVED***data-[side=right]:slide-in-from-left-2***REMOVED***data-[side=top]:slide-in-from-bottom-2",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
MenubarSubContent.displayName***REMOVED***=***REMOVED***MenubarPrimitive.SubContent.displayName

const***REMOVED***MenubarContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***MenubarPrimitive.Content>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***MenubarPrimitive.Content>
>(
***REMOVED******REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***className,***REMOVED***align***REMOVED***=***REMOVED***"start",***REMOVED***alignOffset***REMOVED***=***REMOVED***-4,***REMOVED***sideOffset***REMOVED***=***REMOVED***8,***REMOVED***...props***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***ref
***REMOVED******REMOVED***)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<MenubarPrimitive.Portal>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<MenubarPrimitive.Content
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***align={align}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***alignOffset={alignOffset}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sideOffset={sideOffset}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"z-50***REMOVED***min-w-[12rem]***REMOVED***overflow-hidden***REMOVED***rounded-md***REMOVED***border***REMOVED***bg-popover***REMOVED***p-1***REMOVED***text-popover-foreground***REMOVED***shadow-md***REMOVED***data-[state=open]:animate-in***REMOVED***data-[state=closed]:fade-out-0***REMOVED***data-[state=open]:fade-in-0***REMOVED***data-[state=closed]:zoom-out-95***REMOVED***data-[state=open]:zoom-in-95***REMOVED***data-[side=bottom]:slide-in-from-top-2***REMOVED***data-[side=left]:slide-in-from-right-2***REMOVED***data-[side=right]:slide-in-from-left-2***REMOVED***data-[side=top]:slide-in-from-bottom-2",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED***</MenubarPrimitive.Portal>
***REMOVED******REMOVED***)
)
MenubarContent.displayName***REMOVED***=***REMOVED***MenubarPrimitive.Content.displayName

const***REMOVED***MenubarItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***MenubarPrimitive.Item>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***MenubarPrimitive.Item>***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***inset?:***REMOVED***boolean
***REMOVED******REMOVED***}
>(({***REMOVED***className,***REMOVED***inset,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<MenubarPrimitive.Item
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"relative***REMOVED***flex***REMOVED***cursor-default***REMOVED***select-none***REMOVED***items-center***REMOVED***rounded-sm***REMOVED***px-2***REMOVED***py-1.5***REMOVED***text-sm***REMOVED***outline-none***REMOVED***focus:bg-accent***REMOVED***focus:text-accent-foreground***REMOVED***data-[disabled]:pointer-events-none***REMOVED***data-[disabled]:opacity-50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***inset***REMOVED***&&***REMOVED***"pl-8",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
MenubarItem.displayName***REMOVED***=***REMOVED***MenubarPrimitive.Item.displayName

const***REMOVED***MenubarCheckboxItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***MenubarPrimitive.CheckboxItem>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***MenubarPrimitive.CheckboxItem>
>(({***REMOVED***className,***REMOVED***children,***REMOVED***checked,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<MenubarPrimitive.CheckboxItem
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"relative***REMOVED***flex***REMOVED***cursor-default***REMOVED***select-none***REMOVED***items-center***REMOVED***rounded-sm***REMOVED***py-1.5***REMOVED***pl-8***REMOVED***pr-2***REMOVED***text-sm***REMOVED***outline-none***REMOVED***focus:bg-accent***REMOVED***focus:text-accent-foreground***REMOVED***data-[disabled]:pointer-events-none***REMOVED***data-[disabled]:opacity-50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***checked={checked}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="absolute***REMOVED***left-2***REMOVED***flex***REMOVED***h-3.5***REMOVED***w-3.5***REMOVED***items-center***REMOVED***justify-center">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<MenubarPrimitive.ItemIndicator>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Check***REMOVED***className="h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</MenubarPrimitive.ItemIndicator>
***REMOVED******REMOVED******REMOVED******REMOVED***</span>
***REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED***</MenubarPrimitive.CheckboxItem>
))
MenubarCheckboxItem.displayName***REMOVED***=***REMOVED***MenubarPrimitive.CheckboxItem.displayName

const***REMOVED***MenubarRadioItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***MenubarPrimitive.RadioItem>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***MenubarPrimitive.RadioItem>
>(({***REMOVED***className,***REMOVED***children,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<MenubarPrimitive.RadioItem
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"relative***REMOVED***flex***REMOVED***cursor-default***REMOVED***select-none***REMOVED***items-center***REMOVED***rounded-sm***REMOVED***py-1.5***REMOVED***pl-8***REMOVED***pr-2***REMOVED***text-sm***REMOVED***outline-none***REMOVED***focus:bg-accent***REMOVED***focus:text-accent-foreground***REMOVED***data-[disabled]:pointer-events-none***REMOVED***data-[disabled]:opacity-50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="absolute***REMOVED***left-2***REMOVED***flex***REMOVED***h-3.5***REMOVED***w-3.5***REMOVED***items-center***REMOVED***justify-center">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<MenubarPrimitive.ItemIndicator>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Circle***REMOVED***className="h-2***REMOVED***w-2***REMOVED***fill-current"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</MenubarPrimitive.ItemIndicator>
***REMOVED******REMOVED******REMOVED******REMOVED***</span>
***REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED***</MenubarPrimitive.RadioItem>
))
MenubarRadioItem.displayName***REMOVED***=***REMOVED***MenubarPrimitive.RadioItem.displayName

const***REMOVED***MenubarLabel***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***MenubarPrimitive.Label>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***MenubarPrimitive.Label>***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***inset?:***REMOVED***boolean
***REMOVED******REMOVED***}
>(({***REMOVED***className,***REMOVED***inset,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<MenubarPrimitive.Label
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"px-2***REMOVED***py-1.5***REMOVED***text-sm***REMOVED***font-semibold",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***inset***REMOVED***&&***REMOVED***"pl-8",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
MenubarLabel.displayName***REMOVED***=***REMOVED***MenubarPrimitive.Label.displayName

const***REMOVED***MenubarSeparator***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***MenubarPrimitive.Separator>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***MenubarPrimitive.Separator>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<MenubarPrimitive.Separator
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("-mx-1***REMOVED***my-1***REMOVED***h-px***REMOVED***bg-muted",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
MenubarSeparator.displayName***REMOVED***=***REMOVED***MenubarPrimitive.Separator.displayName

const***REMOVED***MenubarShortcut***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.HTMLAttributes<HTMLSpanElement>)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<span
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"ml-auto***REMOVED***text-xs***REMOVED***tracking-widest***REMOVED***text-muted-foreground",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}
MenubarShortcut.displayname***REMOVED***=***REMOVED***"MenubarShortcut"

export***REMOVED***{
***REMOVED******REMOVED***Menubar,
***REMOVED******REMOVED***MenubarMenu,
***REMOVED******REMOVED***MenubarTrigger,
***REMOVED******REMOVED***MenubarContent,
***REMOVED******REMOVED***MenubarItem,
***REMOVED******REMOVED***MenubarSeparator,
***REMOVED******REMOVED***MenubarLabel,
***REMOVED******REMOVED***MenubarCheckboxItem,
***REMOVED******REMOVED***MenubarRadioGroup,
***REMOVED******REMOVED***MenubarRadioItem,
***REMOVED******REMOVED***MenubarPortal,
***REMOVED******REMOVED***MenubarSubContent,
***REMOVED******REMOVED***MenubarSubTrigger,
***REMOVED******REMOVED***MenubarGroup,
***REMOVED******REMOVED***MenubarSub,
***REMOVED******REMOVED***MenubarShortcut,
}
