import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED*******REMOVED***as***REMOVED***NavigationMenuPrimitive***REMOVED***from***REMOVED***"@radix-ui/react-navigation-menu"
import***REMOVED***{***REMOVED***cva***REMOVED***}***REMOVED***from***REMOVED***"class-variance-authority"
import***REMOVED***{***REMOVED***ChevronDown***REMOVED***}***REMOVED***from***REMOVED***"lucide-react"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"

const***REMOVED***NavigationMenu***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***NavigationMenuPrimitive.Root>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***NavigationMenuPrimitive.Root>
>(({***REMOVED***className,***REMOVED***children,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<NavigationMenuPrimitive.Root
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"relative***REMOVED***z-10***REMOVED***flex***REMOVED***max-w-max***REMOVED***flex-1***REMOVED***items-center***REMOVED***justify-center",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED***<NavigationMenuViewport***REMOVED***/>
***REMOVED******REMOVED***</NavigationMenuPrimitive.Root>
))
NavigationMenu.displayName***REMOVED***=***REMOVED***NavigationMenuPrimitive.Root.displayName

const***REMOVED***NavigationMenuList***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***NavigationMenuPrimitive.List>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***NavigationMenuPrimitive.List>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<NavigationMenuPrimitive.List
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group***REMOVED***flex***REMOVED***flex-1***REMOVED***list-none***REMOVED***items-center***REMOVED***justify-center***REMOVED***space-x-1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
NavigationMenuList.displayName***REMOVED***=***REMOVED***NavigationMenuPrimitive.List.displayName

const***REMOVED***NavigationMenuItem***REMOVED***=***REMOVED***NavigationMenuPrimitive.Item

const***REMOVED***navigationMenuTriggerStyle***REMOVED***=***REMOVED***cva(
***REMOVED******REMOVED***"group***REMOVED***inline-flex***REMOVED***h-10***REMOVED***w-max***REMOVED***items-center***REMOVED***justify-center***REMOVED***rounded-md***REMOVED***bg-background***REMOVED***px-4***REMOVED***py-2***REMOVED***text-sm***REMOVED***font-medium***REMOVED***transition-colors***REMOVED***hover:bg-accent***REMOVED***hover:text-accent-foreground***REMOVED***focus:bg-accent***REMOVED***focus:text-accent-foreground***REMOVED***focus:outline-none***REMOVED***disabled:pointer-events-none***REMOVED***disabled:opacity-50***REMOVED***data-[active]:bg-accent/50***REMOVED***data-[state=open]:bg-accent/50"
)

const***REMOVED***NavigationMenuTrigger***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***NavigationMenuPrimitive.Trigger>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***NavigationMenuPrimitive.Trigger>
>(({***REMOVED***className,***REMOVED***children,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<NavigationMenuPrimitive.Trigger
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(navigationMenuTriggerStyle(),***REMOVED***"group",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***{children}{"***REMOVED***"}
***REMOVED******REMOVED******REMOVED******REMOVED***<ChevronDown
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="relative***REMOVED***top-[1px]***REMOVED***ml-1***REMOVED***h-3***REMOVED***w-3***REMOVED***transition***REMOVED***duration-200***REMOVED***group-data-[state=open]:rotate-180"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-hidden="true"
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***</NavigationMenuPrimitive.Trigger>
))
NavigationMenuTrigger.displayName***REMOVED***=***REMOVED***NavigationMenuPrimitive.Trigger.displayName

const***REMOVED***NavigationMenuContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***NavigationMenuPrimitive.Content>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***NavigationMenuPrimitive.Content>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<NavigationMenuPrimitive.Content
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"left-0***REMOVED***top-0***REMOVED***w-full***REMOVED***data-[motion^=from-]:animate-in***REMOVED***data-[motion^=to-]:animate-out***REMOVED***data-[motion^=from-]:fade-in***REMOVED***data-[motion^=to-]:fade-out***REMOVED***data-[motion=from-end]:slide-in-from-right-52***REMOVED***data-[motion=from-start]:slide-in-from-left-52***REMOVED***data-[motion=to-end]:slide-out-to-right-52***REMOVED***data-[motion=to-start]:slide-out-to-left-52***REMOVED***md:absolute***REMOVED***md:w-auto***REMOVED***",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
NavigationMenuContent.displayName***REMOVED***=***REMOVED***NavigationMenuPrimitive.Content.displayName

const***REMOVED***NavigationMenuLink***REMOVED***=***REMOVED***NavigationMenuPrimitive.Link

const***REMOVED***NavigationMenuViewport***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***NavigationMenuPrimitive.Viewport>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***NavigationMenuPrimitive.Viewport>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<div***REMOVED***className={cn("absolute***REMOVED***left-0***REMOVED***top-full***REMOVED***flex***REMOVED***justify-center")}>
***REMOVED******REMOVED******REMOVED******REMOVED***<NavigationMenuPrimitive.Viewport
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"origin-top-center***REMOVED***relative***REMOVED***mt-1.5***REMOVED***h-[var(--radix-navigation-menu-viewport-height)]***REMOVED***w-full***REMOVED***overflow-hidden***REMOVED***rounded-md***REMOVED***border***REMOVED***bg-popover***REMOVED***text-popover-foreground***REMOVED***shadow-lg***REMOVED***data-[state=open]:animate-in***REMOVED***data-[state=closed]:animate-out***REMOVED***data-[state=closed]:zoom-out-95***REMOVED***data-[state=open]:zoom-in-90***REMOVED***md:w-[var(--radix-navigation-menu-viewport-width)]",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***</div>
))
NavigationMenuViewport.displayName***REMOVED***=
***REMOVED******REMOVED***NavigationMenuPrimitive.Viewport.displayName

const***REMOVED***NavigationMenuIndicator***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***NavigationMenuPrimitive.Indicator>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***NavigationMenuPrimitive.Indicator>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<NavigationMenuPrimitive.Indicator
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"top-full***REMOVED***z-[1]***REMOVED***flex***REMOVED***h-1.5***REMOVED***items-end***REMOVED***justify-center***REMOVED***overflow-hidden***REMOVED***data-[state=visible]:animate-in***REMOVED***data-[state=hidden]:animate-out***REMOVED***data-[state=hidden]:fade-out***REMOVED***data-[state=visible]:fade-in",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="relative***REMOVED***top-[60%]***REMOVED***h-2***REMOVED***w-2***REMOVED***rotate-45***REMOVED***rounded-tl-sm***REMOVED***bg-border***REMOVED***shadow-md"***REMOVED***/>
***REMOVED******REMOVED***</NavigationMenuPrimitive.Indicator>
))
NavigationMenuIndicator.displayName***REMOVED***=
***REMOVED******REMOVED***NavigationMenuPrimitive.Indicator.displayName

export***REMOVED***{
***REMOVED******REMOVED***navigationMenuTriggerStyle,
***REMOVED******REMOVED***NavigationMenu,
***REMOVED******REMOVED***NavigationMenuList,
***REMOVED******REMOVED***NavigationMenuItem,
***REMOVED******REMOVED***NavigationMenuContent,
***REMOVED******REMOVED***NavigationMenuTrigger,
***REMOVED******REMOVED***NavigationMenuLink,
***REMOVED******REMOVED***NavigationMenuIndicator,
***REMOVED******REMOVED***NavigationMenuViewport,
}
