import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED***{***REMOVED***ChevronLeft,***REMOVED***ChevronRight,***REMOVED***MoreHorizontal***REMOVED***}***REMOVED***from***REMOVED***"lucide-react"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"
import***REMOVED***{***REMOVED***ButtonProps,***REMOVED***buttonVariants***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/button"

const***REMOVED***Pagination***REMOVED***=***REMOVED***({***REMOVED***className,***REMOVED***...props***REMOVED***}:***REMOVED***React.ComponentProps<"nav">)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<nav
***REMOVED******REMOVED******REMOVED******REMOVED***role="navigation"
***REMOVED******REMOVED******REMOVED******REMOVED***aria-label="pagination"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("mx-auto***REMOVED***flex***REMOVED***w-full***REMOVED***justify-center",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
)
Pagination.displayName***REMOVED***=***REMOVED***"Pagination"

const***REMOVED***PaginationContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLUListElement,
***REMOVED******REMOVED***React.ComponentProps<"ul">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<ul
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("flex***REMOVED***flex-row***REMOVED***items-center***REMOVED***gap-1",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
PaginationContent.displayName***REMOVED***=***REMOVED***"PaginationContent"

const***REMOVED***PaginationItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLLIElement,
***REMOVED******REMOVED***React.ComponentProps<"li">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<li***REMOVED***ref={ref}***REMOVED***className={cn("",***REMOVED***className)}***REMOVED***{...props}***REMOVED***/>
))
PaginationItem.displayName***REMOVED***=***REMOVED***"PaginationItem"

type***REMOVED***PaginationLinkProps***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***isActive?:***REMOVED***boolean
}***REMOVED***&***REMOVED***Pick<ButtonProps,***REMOVED***"size">***REMOVED***&
***REMOVED******REMOVED***React.ComponentProps<"a">

const***REMOVED***PaginationLink***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***isActive,
***REMOVED******REMOVED***size***REMOVED***=***REMOVED***"icon",
***REMOVED******REMOVED***...props
}:***REMOVED***PaginationLinkProps)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<a
***REMOVED******REMOVED******REMOVED******REMOVED***aria-current={isActive***REMOVED***?***REMOVED***"page"***REMOVED***:***REMOVED***undefined}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***buttonVariants({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant:***REMOVED***isActive***REMOVED***?***REMOVED***"outline"***REMOVED***:***REMOVED***"ghost",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
)
PaginationLink.displayName***REMOVED***=***REMOVED***"PaginationLink"

const***REMOVED***PaginationPrevious***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***PaginationLink>)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<PaginationLink
***REMOVED******REMOVED******REMOVED******REMOVED***aria-label="Go***REMOVED***to***REMOVED***previous***REMOVED***page"
***REMOVED******REMOVED******REMOVED******REMOVED***size="default"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("gap-1***REMOVED***pl-2.5",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<ChevronLeft***REMOVED***className="h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED***<span>Previous</span>
***REMOVED******REMOVED***</PaginationLink>
)
PaginationPrevious.displayName***REMOVED***=***REMOVED***"PaginationPrevious"

const***REMOVED***PaginationNext***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***PaginationLink>)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<PaginationLink
***REMOVED******REMOVED******REMOVED******REMOVED***aria-label="Go***REMOVED***to***REMOVED***next***REMOVED***page"
***REMOVED******REMOVED******REMOVED******REMOVED***size="default"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("gap-1***REMOVED***pr-2.5",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<span>Next</span>
***REMOVED******REMOVED******REMOVED******REMOVED***<ChevronRight***REMOVED***className="h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED***</PaginationLink>
)
PaginationNext.displayName***REMOVED***=***REMOVED***"PaginationNext"

const***REMOVED***PaginationEllipsis***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<"span">)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<span
***REMOVED******REMOVED******REMOVED******REMOVED***aria-hidden
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("flex***REMOVED***h-9***REMOVED***w-9***REMOVED***items-center***REMOVED***justify-center",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<MoreHorizontal***REMOVED***className="h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="sr-only">More***REMOVED***pages</span>
***REMOVED******REMOVED***</span>
)
PaginationEllipsis.displayName***REMOVED***=***REMOVED***"PaginationEllipsis"

export***REMOVED***{
***REMOVED******REMOVED***Pagination,
***REMOVED******REMOVED***PaginationContent,
***REMOVED******REMOVED***PaginationEllipsis,
***REMOVED******REMOVED***PaginationItem,
***REMOVED******REMOVED***PaginationLink,
***REMOVED******REMOVED***PaginationNext,
***REMOVED******REMOVED***PaginationPrevious,
}
