import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED*******REMOVED***as***REMOVED***SelectPrimitive***REMOVED***from***REMOVED***"@radix-ui/react-select"
import***REMOVED***{***REMOVED***Check,***REMOVED***ChevronDown,***REMOVED***ChevronUp***REMOVED***}***REMOVED***from***REMOVED***"lucide-react"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"

const***REMOVED***Select***REMOVED***=***REMOVED***SelectPrimitive.Root

const***REMOVED***SelectGroup***REMOVED***=***REMOVED***SelectPrimitive.Group

const***REMOVED***SelectValue***REMOVED***=***REMOVED***SelectPrimitive.Value

const***REMOVED***SelectTrigger***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***SelectPrimitive.Trigger>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***SelectPrimitive.Trigger>
>(({***REMOVED***className,***REMOVED***children,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<SelectPrimitive.Trigger
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***h-10***REMOVED***w-full***REMOVED***items-center***REMOVED***justify-between***REMOVED***rounded-md***REMOVED***border***REMOVED***border-input***REMOVED***bg-background***REMOVED***px-3***REMOVED***py-2***REMOVED***text-sm***REMOVED***ring-offset-background***REMOVED***placeholder:text-muted-foreground***REMOVED***focus:outline-none***REMOVED***focus:ring-2***REMOVED***focus:ring-ring***REMOVED***focus:ring-offset-2***REMOVED***disabled:cursor-not-allowed***REMOVED***disabled:opacity-50***REMOVED***[&>span]:line-clamp-1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED***<SelectPrimitive.Icon***REMOVED***asChild>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ChevronDown***REMOVED***className="h-4***REMOVED***w-4***REMOVED***opacity-50"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED***</SelectPrimitive.Icon>
***REMOVED******REMOVED***</SelectPrimitive.Trigger>
))
SelectTrigger.displayName***REMOVED***=***REMOVED***SelectPrimitive.Trigger.displayName

const***REMOVED***SelectScrollUpButton***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***SelectPrimitive.ScrollUpButton>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***SelectPrimitive.ScrollUpButton>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<SelectPrimitive.ScrollUpButton
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***cursor-default***REMOVED***items-center***REMOVED***justify-center***REMOVED***py-1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<ChevronUp***REMOVED***className="h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED***</SelectPrimitive.ScrollUpButton>
))
SelectScrollUpButton.displayName***REMOVED***=***REMOVED***SelectPrimitive.ScrollUpButton.displayName

const***REMOVED***SelectScrollDownButton***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***SelectPrimitive.ScrollDownButton>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***SelectPrimitive.ScrollDownButton>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<SelectPrimitive.ScrollDownButton
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***cursor-default***REMOVED***items-center***REMOVED***justify-center***REMOVED***py-1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<ChevronDown***REMOVED***className="h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED***</SelectPrimitive.ScrollDownButton>
))
SelectScrollDownButton.displayName***REMOVED***=
***REMOVED******REMOVED***SelectPrimitive.ScrollDownButton.displayName

const***REMOVED***SelectContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***SelectPrimitive.Content>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***SelectPrimitive.Content>
>(({***REMOVED***className,***REMOVED***children,***REMOVED***position***REMOVED***=***REMOVED***"popper",***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<SelectPrimitive.Portal>
***REMOVED******REMOVED******REMOVED******REMOVED***<SelectPrimitive.Content
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"relative***REMOVED***z-50***REMOVED***max-h-96***REMOVED***min-w-[8rem]***REMOVED***overflow-hidden***REMOVED***rounded-md***REMOVED***border***REMOVED***bg-popover***REMOVED***text-popover-foreground***REMOVED***shadow-md***REMOVED***data-[state=open]:animate-in***REMOVED***data-[state=closed]:animate-out***REMOVED***data-[state=closed]:fade-out-0***REMOVED***data-[state=open]:fade-in-0***REMOVED***data-[state=closed]:zoom-out-95***REMOVED***data-[state=open]:zoom-in-95***REMOVED***data-[side=bottom]:slide-in-from-top-2***REMOVED***data-[side=left]:slide-in-from-right-2***REMOVED***data-[side=right]:slide-in-from-left-2***REMOVED***data-[side=top]:slide-in-from-bottom-2",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***position***REMOVED***===***REMOVED***"popper"***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"data-[side=bottom]:translate-y-1***REMOVED***data-[side=left]:-translate-x-1***REMOVED***data-[side=right]:translate-x-1***REMOVED***data-[side=top]:-translate-y-1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***position={position}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SelectScrollUpButton***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SelectPrimitive.Viewport
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"p-1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***position***REMOVED***===***REMOVED***"popper"***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"h-[var(--radix-select-trigger-height)]***REMOVED***w-full***REMOVED***min-w-[var(--radix-select-trigger-width)]"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</SelectPrimitive.Viewport>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SelectScrollDownButton***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED***</SelectPrimitive.Content>
***REMOVED******REMOVED***</SelectPrimitive.Portal>
))
SelectContent.displayName***REMOVED***=***REMOVED***SelectPrimitive.Content.displayName

const***REMOVED***SelectLabel***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***SelectPrimitive.Label>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***SelectPrimitive.Label>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<SelectPrimitive.Label
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("py-1.5***REMOVED***pl-8***REMOVED***pr-2***REMOVED***text-sm***REMOVED***font-semibold",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
SelectLabel.displayName***REMOVED***=***REMOVED***SelectPrimitive.Label.displayName

const***REMOVED***SelectItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***SelectPrimitive.Item>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***SelectPrimitive.Item>
>(({***REMOVED***className,***REMOVED***children,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<SelectPrimitive.Item
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"relative***REMOVED***flex***REMOVED***w-full***REMOVED***cursor-default***REMOVED***select-none***REMOVED***items-center***REMOVED***rounded-sm***REMOVED***py-1.5***REMOVED***pl-8***REMOVED***pr-2***REMOVED***text-sm***REMOVED***outline-none***REMOVED***focus:bg-accent***REMOVED***focus:text-accent-foreground***REMOVED***data-[disabled]:pointer-events-none***REMOVED***data-[disabled]:opacity-50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="absolute***REMOVED***left-2***REMOVED***flex***REMOVED***h-3.5***REMOVED***w-3.5***REMOVED***items-center***REMOVED***justify-center">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SelectPrimitive.ItemIndicator>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Check***REMOVED***className="h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</SelectPrimitive.ItemIndicator>
***REMOVED******REMOVED******REMOVED******REMOVED***</span>

***REMOVED******REMOVED******REMOVED******REMOVED***<SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText>
***REMOVED******REMOVED***</SelectPrimitive.Item>
))
SelectItem.displayName***REMOVED***=***REMOVED***SelectPrimitive.Item.displayName

const***REMOVED***SelectSeparator***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***SelectPrimitive.Separator>,
***REMOVED******REMOVED***React.ComponentPropsWithoutRef<typeof***REMOVED***SelectPrimitive.Separator>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<SelectPrimitive.Separator
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("-mx-1***REMOVED***my-1***REMOVED***h-px***REMOVED***bg-muted",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
SelectSeparator.displayName***REMOVED***=***REMOVED***SelectPrimitive.Separator.displayName

export***REMOVED***{
***REMOVED******REMOVED***Select,
***REMOVED******REMOVED***SelectGroup,
***REMOVED******REMOVED***SelectValue,
***REMOVED******REMOVED***SelectTrigger,
***REMOVED******REMOVED***SelectContent,
***REMOVED******REMOVED***SelectLabel,
***REMOVED******REMOVED***SelectItem,
***REMOVED******REMOVED***SelectSeparator,
***REMOVED******REMOVED***SelectScrollUpButton,
***REMOVED******REMOVED***SelectScrollDownButton,
}
