import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED***{***REMOVED***Slot***REMOVED***}***REMOVED***from***REMOVED***"@radix-ui/react-slot"
import***REMOVED***{***REMOVED***VariantProps,***REMOVED***cva***REMOVED***}***REMOVED***from***REMOVED***"class-variance-authority"
import***REMOVED***{***REMOVED***PanelLeft***REMOVED***}***REMOVED***from***REMOVED***"lucide-react"

import***REMOVED***{***REMOVED***useIsMobile***REMOVED***}***REMOVED***from***REMOVED***"@/hooks/use-mobile"
import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"
import***REMOVED***{***REMOVED***Button***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/button"
import***REMOVED***{***REMOVED***Input***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/input"
import***REMOVED***{***REMOVED***Separator***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/separator"
import***REMOVED***{***REMOVED***Sheet,***REMOVED***SheetContent***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/sheet"
import***REMOVED***{***REMOVED***Skeleton***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/skeleton"
import***REMOVED***{
***REMOVED******REMOVED***Tooltip,
***REMOVED******REMOVED***TooltipContent,
***REMOVED******REMOVED***TooltipProvider,
***REMOVED******REMOVED***TooltipTrigger,
}***REMOVED***from***REMOVED***"@/components/ui/tooltip"

const***REMOVED***SIDEBAR_COOKIE_NAME***REMOVED***=***REMOVED***"sidebar:state"
const***REMOVED***SIDEBAR_COOKIE_MAX_AGE***REMOVED***=***REMOVED***60***REMOVED*******REMOVED***60***REMOVED*******REMOVED***24***REMOVED*******REMOVED***7
const***REMOVED***SIDEBAR_WIDTH***REMOVED***=***REMOVED***"16rem"
const***REMOVED***SIDEBAR_WIDTH_MOBILE***REMOVED***=***REMOVED***"18rem"
const***REMOVED***SIDEBAR_WIDTH_ICON***REMOVED***=***REMOVED***"3rem"
const***REMOVED***SIDEBAR_KEYBOARD_SHORTCUT***REMOVED***=***REMOVED***"b"

type***REMOVED***SidebarContext***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***state:***REMOVED***"expanded"***REMOVED***|***REMOVED***"collapsed"
***REMOVED******REMOVED***open:***REMOVED***boolean
***REMOVED******REMOVED***setOpen:***REMOVED***(open:***REMOVED***boolean)***REMOVED***=>***REMOVED***void
***REMOVED******REMOVED***openMobile:***REMOVED***boolean
***REMOVED******REMOVED***setOpenMobile:***REMOVED***(open:***REMOVED***boolean)***REMOVED***=>***REMOVED***void
***REMOVED******REMOVED***isMobile:***REMOVED***boolean
***REMOVED******REMOVED***toggleSidebar:***REMOVED***()***REMOVED***=>***REMOVED***void
}

const***REMOVED***SidebarContext***REMOVED***=***REMOVED***React.createContext<SidebarContext***REMOVED***|***REMOVED***null>(null)

function***REMOVED***useSidebar()***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***context***REMOVED***=***REMOVED***React.useContext(SidebarContext)
***REMOVED******REMOVED***if***REMOVED***(!context)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***new***REMOVED***Error("useSidebar***REMOVED***must***REMOVED***be***REMOVED***used***REMOVED***within***REMOVED***a***REMOVED***SidebarProvider.")
***REMOVED******REMOVED***}

***REMOVED******REMOVED***return***REMOVED***context
}

const***REMOVED***SidebarProvider***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***defaultOpen?:***REMOVED***boolean
***REMOVED******REMOVED******REMOVED******REMOVED***open?:***REMOVED***boolean
***REMOVED******REMOVED******REMOVED******REMOVED***onOpenChange?:***REMOVED***(open:***REMOVED***boolean)***REMOVED***=>***REMOVED***void
***REMOVED******REMOVED***}
>(
***REMOVED******REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***defaultOpen***REMOVED***=***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***open:***REMOVED***openProp,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onOpenChange:***REMOVED***setOpenProp,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***style,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***children,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...props
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***ref
***REMOVED******REMOVED***)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***isMobile***REMOVED***=***REMOVED***useIsMobile()
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***[openMobile,***REMOVED***setOpenMobile]***REMOVED***=***REMOVED***React.useState(false)

***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***This***REMOVED***is***REMOVED***the***REMOVED***internal***REMOVED***state***REMOVED***of***REMOVED***the***REMOVED***sidebar.
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***We***REMOVED***use***REMOVED***openProp***REMOVED***and***REMOVED***setOpenProp***REMOVED***for***REMOVED***control***REMOVED***from***REMOVED***outside***REMOVED***the***REMOVED***component.
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***[_open,***REMOVED***_setOpen]***REMOVED***=***REMOVED***React.useState(defaultOpen)
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***open***REMOVED***=***REMOVED***openProp***REMOVED***??***REMOVED***_open
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***setOpen***REMOVED***=***REMOVED***React.useCallback(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***(value:***REMOVED***boolean***REMOVED***|***REMOVED***((value:***REMOVED***boolean)***REMOVED***=>***REMOVED***boolean))***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***openState***REMOVED***=***REMOVED***typeof***REMOVED***value***REMOVED***===***REMOVED***"function"***REMOVED***?***REMOVED***value(open)***REMOVED***:***REMOVED***value
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(setOpenProp)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setOpenProp(openState)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***_setOpen(openState)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***This***REMOVED***sets***REMOVED***the***REMOVED***cookie***REMOVED***to***REMOVED***keep***REMOVED***the***REMOVED***sidebar***REMOVED***state.
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***document.cookie***REMOVED***=***REMOVED***`${SIDEBAR_COOKIE_NAME}=${openState};***REMOVED***path=/;***REMOVED***max-age=${SIDEBAR_COOKIE_MAX_AGE}`
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***[setOpenProp,***REMOVED***open]
***REMOVED******REMOVED******REMOVED******REMOVED***)

***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Helper***REMOVED***to***REMOVED***toggle***REMOVED***the***REMOVED***sidebar.
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***toggleSidebar***REMOVED***=***REMOVED***React.useCallback(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***isMobile
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***setOpenMobile((open)***REMOVED***=>***REMOVED***!open)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***setOpen((open)***REMOVED***=>***REMOVED***!open)
***REMOVED******REMOVED******REMOVED******REMOVED***},***REMOVED***[isMobile,***REMOVED***setOpen,***REMOVED***setOpenMobile])

***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Adds***REMOVED***a***REMOVED***keyboard***REMOVED***shortcut***REMOVED***to***REMOVED***toggle***REMOVED***the***REMOVED***sidebar.
***REMOVED******REMOVED******REMOVED******REMOVED***React.useEffect(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***handleKeyDown***REMOVED***=***REMOVED***(event:***REMOVED***KeyboardEvent)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***event.key***REMOVED***===***REMOVED***SIDEBAR_KEYBOARD_SHORTCUT***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***(event.metaKey***REMOVED***||***REMOVED***event.ctrlKey)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***event.preventDefault()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***toggleSidebar()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***window.addEventListener("keydown",***REMOVED***handleKeyDown)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***()***REMOVED***=>***REMOVED***window.removeEventListener("keydown",***REMOVED***handleKeyDown)
***REMOVED******REMOVED******REMOVED******REMOVED***},***REMOVED***[toggleSidebar])

***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***We***REMOVED***add***REMOVED***a***REMOVED***state***REMOVED***so***REMOVED***that***REMOVED***we***REMOVED***can***REMOVED***do***REMOVED***data-state="expanded"***REMOVED***or***REMOVED***"collapsed".
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***This***REMOVED***makes***REMOVED***it***REMOVED***easier***REMOVED***to***REMOVED***style***REMOVED***the***REMOVED***sidebar***REMOVED***with***REMOVED***Tailwind***REMOVED***classes.
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***state***REMOVED***=***REMOVED***open***REMOVED***?***REMOVED***"expanded"***REMOVED***:***REMOVED***"collapsed"

***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***contextValue***REMOVED***=***REMOVED***React.useMemo<SidebarContext>(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***()***REMOVED***=>***REMOVED***({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***state,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***open,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setOpen,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isMobile,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***openMobile,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setOpenMobile,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***toggleSidebar,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***[state,***REMOVED***open,***REMOVED***setOpen,***REMOVED***isMobile,***REMOVED***openMobile,***REMOVED***setOpenMobile,***REMOVED***toggleSidebar]
***REMOVED******REMOVED******REMOVED******REMOVED***)

***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SidebarContext.Provider***REMOVED***value={contextValue}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<TooltipProvider***REMOVED***delayDuration={0}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***style={
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"--sidebar-width":***REMOVED***SIDEBAR_WIDTH,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"--sidebar-width-icon":***REMOVED***SIDEBAR_WIDTH_ICON,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...style,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***as***REMOVED***React.CSSProperties
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group/sidebar-wrapper***REMOVED***flex***REMOVED***min-h-svh***REMOVED***w-full***REMOVED***has-[[data-variant=inset]]:bg-sidebar",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</TooltipProvider>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</SidebarContext.Provider>
***REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED***}
)
SidebarProvider.displayName***REMOVED***=***REMOVED***"SidebarProvider"

const***REMOVED***Sidebar***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***side?:***REMOVED***"left"***REMOVED***|***REMOVED***"right"
***REMOVED******REMOVED******REMOVED******REMOVED***variant?:***REMOVED***"sidebar"***REMOVED***|***REMOVED***"floating"***REMOVED***|***REMOVED***"inset"
***REMOVED******REMOVED******REMOVED******REMOVED***collapsible?:***REMOVED***"offcanvas"***REMOVED***|***REMOVED***"icon"***REMOVED***|***REMOVED***"none"
***REMOVED******REMOVED***}
>(
***REMOVED******REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***side***REMOVED***=***REMOVED***"left",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant***REMOVED***=***REMOVED***"sidebar",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***collapsible***REMOVED***=***REMOVED***"offcanvas",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***children,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...props
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***ref
***REMOVED******REMOVED***)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***isMobile,***REMOVED***state,***REMOVED***openMobile,***REMOVED***setOpenMobile***REMOVED***}***REMOVED***=***REMOVED***useSidebar()

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(collapsible***REMOVED***===***REMOVED***"none")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***h-full***REMOVED***w-[--sidebar-width]***REMOVED***flex-col***REMOVED***bg-sidebar***REMOVED***text-sidebar-foreground",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(isMobile)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Sheet***REMOVED***open={openMobile}***REMOVED***onOpenChange={setOpenMobile}***REMOVED***{...props}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SheetContent
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="sidebar"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-mobile="true"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="w-[--sidebar-width]***REMOVED***bg-sidebar***REMOVED***p-0***REMOVED***text-sidebar-foreground***REMOVED***[&>button]:hidden"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***style={
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"--sidebar-width":***REMOVED***SIDEBAR_WIDTH_MOBILE,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***as***REMOVED***React.CSSProperties
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***side={side}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex***REMOVED***h-full***REMOVED***w-full***REMOVED***flex-col">{children}</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</SheetContent>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Sheet>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="group***REMOVED***peer***REMOVED***hidden***REMOVED***md:block***REMOVED***text-sidebar-foreground"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-state={state}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-collapsible={state***REMOVED***===***REMOVED***"collapsed"***REMOVED***?***REMOVED***collapsible***REMOVED***:***REMOVED***""}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-variant={variant}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-side={side}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***This***REMOVED***is***REMOVED***what***REMOVED***handles***REMOVED***the***REMOVED***sidebar***REMOVED***gap***REMOVED***on***REMOVED***desktop***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"duration-200***REMOVED***relative***REMOVED***h-svh***REMOVED***w-[--sidebar-width]***REMOVED***bg-transparent***REMOVED***transition-[width]***REMOVED***ease-linear",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group-data-[collapsible=offcanvas]:w-0",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group-data-[side=right]:rotate-180",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant***REMOVED***===***REMOVED***"floating"***REMOVED***||***REMOVED***variant***REMOVED***===***REMOVED***"inset"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***"group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)_+_theme(spacing.4))]"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***"group-data-[collapsible=icon]:w-[--sidebar-width-icon]"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"duration-200***REMOVED***fixed***REMOVED***inset-y-0***REMOVED***z-10***REMOVED***hidden***REMOVED***h-svh***REMOVED***w-[--sidebar-width]***REMOVED***transition-[left,right,width]***REMOVED***ease-linear***REMOVED***md:flex",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***side***REMOVED***===***REMOVED***"left"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***"left-0***REMOVED***group-data-[collapsible=offcanvas]:left-[calc(var(--sidebar-width)*-1)]"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***"right-0***REMOVED***group-data-[collapsible=offcanvas]:right-[calc(var(--sidebar-width)*-1)]",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Adjust***REMOVED***the***REMOVED***padding***REMOVED***for***REMOVED***floating***REMOVED***and***REMOVED***inset***REMOVED***variants.
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant***REMOVED***===***REMOVED***"floating"***REMOVED***||***REMOVED***variant***REMOVED***===***REMOVED***"inset"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***"p-2***REMOVED***group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)_+_theme(spacing.4)_+2px)]"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***"group-data-[collapsible=icon]:w-[--sidebar-width-icon]***REMOVED***group-data-[side=left]:border-r***REMOVED***group-data-[side=right]:border-l",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="sidebar"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="flex***REMOVED***h-full***REMOVED***w-full***REMOVED***flex-col***REMOVED***bg-sidebar***REMOVED***group-data-[variant=floating]:rounded-lg***REMOVED***group-data-[variant=floating]:border***REMOVED***group-data-[variant=floating]:border-sidebar-border***REMOVED***group-data-[variant=floating]:shadow"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED***}
)
Sidebar.displayName***REMOVED***=***REMOVED***"Sidebar"

const***REMOVED***SidebarTrigger***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***Button>,
***REMOVED******REMOVED***React.ComponentProps<typeof***REMOVED***Button>
>(({***REMOVED***className,***REMOVED***onClick,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***toggleSidebar***REMOVED***}***REMOVED***=***REMOVED***useSidebar()

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Button
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="trigger"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant="ghost"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size="icon"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("h-7***REMOVED***w-7",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={(event)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick?.(event)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***toggleSidebar()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<PanelLeft***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="sr-only">Toggle***REMOVED***Sidebar</span>
***REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED***)
})
SidebarTrigger.displayName***REMOVED***=***REMOVED***"SidebarTrigger"

const***REMOVED***SidebarRail***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLButtonElement,
***REMOVED******REMOVED***React.ComponentProps<"button">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***toggleSidebar***REMOVED***}***REMOVED***=***REMOVED***useSidebar()

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<button
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="rail"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-label="Toggle***REMOVED***Sidebar"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***tabIndex={-1}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={toggleSidebar}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***title="Toggle***REMOVED***Sidebar"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"absolute***REMOVED***inset-y-0***REMOVED***z-20***REMOVED***hidden***REMOVED***w-4***REMOVED***-translate-x-1/2***REMOVED***transition-all***REMOVED***ease-linear***REMOVED***after:absolute***REMOVED***after:inset-y-0***REMOVED***after:left-1/2***REMOVED***after:w-[2px]***REMOVED***hover:after:bg-sidebar-border***REMOVED***group-data-[side=left]:-right-4***REMOVED***group-data-[side=right]:left-0***REMOVED***sm:flex",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"[[data-side=left]_&]:cursor-w-resize***REMOVED***[[data-side=right]_&]:cursor-e-resize",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"[[data-side=left][data-state=collapsed]_&]:cursor-e-resize***REMOVED***[[data-side=right][data-state=collapsed]_&]:cursor-w-resize",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group-data-[collapsible=offcanvas]:translate-x-0***REMOVED***group-data-[collapsible=offcanvas]:after:left-full***REMOVED***group-data-[collapsible=offcanvas]:hover:bg-sidebar",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"[[data-side=left][data-collapsible=offcanvas]_&]:-right-2",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"[[data-side=right][data-collapsible=offcanvas]_&]:-left-2",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarRail.displayName***REMOVED***=***REMOVED***"SidebarRail"

const***REMOVED***SidebarInset***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"main">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<main
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"relative***REMOVED***flex***REMOVED***min-h-svh***REMOVED***flex-1***REMOVED***flex-col***REMOVED***bg-background",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"peer-data-[variant=inset]:min-h-[calc(100svh-theme(spacing.4))]***REMOVED***md:peer-data-[variant=inset]:m-2***REMOVED***md:peer-data-[state=collapsed]:peer-data-[variant=inset]:ml-2***REMOVED***md:peer-data-[variant=inset]:ml-0***REMOVED***md:peer-data-[variant=inset]:rounded-xl***REMOVED***md:peer-data-[variant=inset]:shadow",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarInset.displayName***REMOVED***=***REMOVED***"SidebarInset"

const***REMOVED***SidebarInput***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***Input>,
***REMOVED******REMOVED***React.ComponentProps<typeof***REMOVED***Input>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Input
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="input"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"h-8***REMOVED***w-full***REMOVED***bg-background***REMOVED***shadow-none***REMOVED***focus-visible:ring-2***REMOVED***focus-visible:ring-sidebar-ring",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarInput.displayName***REMOVED***=***REMOVED***"SidebarInput"

const***REMOVED***SidebarHeader***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="header"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("flex***REMOVED***flex-col***REMOVED***gap-2***REMOVED***p-2",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarHeader.displayName***REMOVED***=***REMOVED***"SidebarHeader"

const***REMOVED***SidebarFooter***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="footer"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("flex***REMOVED***flex-col***REMOVED***gap-2***REMOVED***p-2",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarFooter.displayName***REMOVED***=***REMOVED***"SidebarFooter"

const***REMOVED***SidebarSeparator***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***React.ElementRef<typeof***REMOVED***Separator>,
***REMOVED******REMOVED***React.ComponentProps<typeof***REMOVED***Separator>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Separator
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="separator"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("mx-2***REMOVED***w-auto***REMOVED***bg-sidebar-border",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarSeparator.displayName***REMOVED***=***REMOVED***"SidebarSeparator"

const***REMOVED***SidebarContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="content"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***min-h-0***REMOVED***flex-1***REMOVED***flex-col***REMOVED***gap-2***REMOVED***overflow-auto***REMOVED***group-data-[collapsible=icon]:overflow-hidden",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarContent.displayName***REMOVED***=***REMOVED***"SidebarContent"

const***REMOVED***SidebarGroup***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="group"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("relative***REMOVED***flex***REMOVED***w-full***REMOVED***min-w-0***REMOVED***flex-col***REMOVED***p-2",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarGroup.displayName***REMOVED***=***REMOVED***"SidebarGroup"

const***REMOVED***SidebarGroupLabel***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">***REMOVED***&***REMOVED***{***REMOVED***asChild?:***REMOVED***boolean***REMOVED***}
>(({***REMOVED***className,***REMOVED***asChild***REMOVED***=***REMOVED***false,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***Comp***REMOVED***=***REMOVED***asChild***REMOVED***?***REMOVED***Slot***REMOVED***:***REMOVED***"div"

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Comp
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="group-label"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"duration-200***REMOVED***flex***REMOVED***h-8***REMOVED***shrink-0***REMOVED***items-center***REMOVED***rounded-md***REMOVED***px-2***REMOVED***text-xs***REMOVED***font-medium***REMOVED***text-sidebar-foreground/70***REMOVED***outline-none***REMOVED***ring-sidebar-ring***REMOVED***transition-[margin,opa]***REMOVED***ease-linear***REMOVED***focus-visible:ring-2***REMOVED***[&>svg]:size-4***REMOVED***[&>svg]:shrink-0",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group-data-[collapsible=icon]:-mt-8***REMOVED***group-data-[collapsible=icon]:opacity-0",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarGroupLabel.displayName***REMOVED***=***REMOVED***"SidebarGroupLabel"

const***REMOVED***SidebarGroupAction***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLButtonElement,
***REMOVED******REMOVED***React.ComponentProps<"button">***REMOVED***&***REMOVED***{***REMOVED***asChild?:***REMOVED***boolean***REMOVED***}
>(({***REMOVED***className,***REMOVED***asChild***REMOVED***=***REMOVED***false,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***Comp***REMOVED***=***REMOVED***asChild***REMOVED***?***REMOVED***Slot***REMOVED***:***REMOVED***"button"

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Comp
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="group-action"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"absolute***REMOVED***right-3***REMOVED***top-3.5***REMOVED***flex***REMOVED***aspect-square***REMOVED***w-5***REMOVED***items-center***REMOVED***justify-center***REMOVED***rounded-md***REMOVED***p-0***REMOVED***text-sidebar-foreground***REMOVED***outline-none***REMOVED***ring-sidebar-ring***REMOVED***transition-transform***REMOVED***hover:bg-sidebar-accent***REMOVED***hover:text-sidebar-accent-foreground***REMOVED***focus-visible:ring-2***REMOVED***[&>svg]:size-4***REMOVED***[&>svg]:shrink-0",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Increases***REMOVED***the***REMOVED***hit***REMOVED***area***REMOVED***of***REMOVED***the***REMOVED***button***REMOVED***on***REMOVED***mobile.
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"after:absolute***REMOVED***after:-inset-2***REMOVED***after:md:hidden",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group-data-[collapsible=icon]:hidden",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarGroupAction.displayName***REMOVED***=***REMOVED***"SidebarGroupAction"

const***REMOVED***SidebarGroupContent***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="group-content"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("w-full***REMOVED***text-sm",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
SidebarGroupContent.displayName***REMOVED***=***REMOVED***"SidebarGroupContent"

const***REMOVED***SidebarMenu***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLUListElement,
***REMOVED******REMOVED***React.ComponentProps<"ul">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<ul
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="menu"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("flex***REMOVED***w-full***REMOVED***min-w-0***REMOVED***flex-col***REMOVED***gap-1",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
SidebarMenu.displayName***REMOVED***=***REMOVED***"SidebarMenu"

const***REMOVED***SidebarMenuItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLLIElement,
***REMOVED******REMOVED***React.ComponentProps<"li">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<li
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="menu-item"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("group/menu-item***REMOVED***relative",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
SidebarMenuItem.displayName***REMOVED***=***REMOVED***"SidebarMenuItem"

const***REMOVED***sidebarMenuButtonVariants***REMOVED***=***REMOVED***cva(
***REMOVED******REMOVED***"peer/menu-button***REMOVED***flex***REMOVED***w-full***REMOVED***items-center***REMOVED***gap-2***REMOVED***overflow-hidden***REMOVED***rounded-md***REMOVED***p-2***REMOVED***text-left***REMOVED***text-sm***REMOVED***outline-none***REMOVED***ring-sidebar-ring***REMOVED***transition-[width,height,padding]***REMOVED***hover:bg-sidebar-accent***REMOVED***hover:text-sidebar-accent-foreground***REMOVED***focus-visible:ring-2***REMOVED***active:bg-sidebar-accent***REMOVED***active:text-sidebar-accent-foreground***REMOVED***disabled:pointer-events-none***REMOVED***disabled:opacity-50***REMOVED***group-has-[[data-sidebar=menu-action]]/menu-item:pr-8***REMOVED***aria-disabled:pointer-events-none***REMOVED***aria-disabled:opacity-50***REMOVED***data-[active=true]:bg-sidebar-accent***REMOVED***data-[active=true]:font-medium***REMOVED***data-[active=true]:text-sidebar-accent-foreground***REMOVED***data-[state=open]:hover:bg-sidebar-accent***REMOVED***data-[state=open]:hover:text-sidebar-accent-foreground***REMOVED***group-data-[collapsible=icon]:!size-8***REMOVED***group-data-[collapsible=icon]:!p-2***REMOVED***[&>span:last-child]:truncate***REMOVED***[&>svg]:size-4***REMOVED***[&>svg]:shrink-0",
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***variants:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***default:***REMOVED***"hover:bg-sidebar-accent***REMOVED***hover:text-sidebar-accent-foreground",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***outline:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"bg-background***REMOVED***shadow-[0_0_0_1px_hsl(var(--sidebar-border))]***REMOVED***hover:bg-sidebar-accent***REMOVED***hover:text-sidebar-accent-foreground***REMOVED***hover:shadow-[0_0_0_1px_hsl(var(--sidebar-accent))]",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***default:***REMOVED***"h-8***REMOVED***text-sm",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sm:***REMOVED***"h-7***REMOVED***text-xs",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***lg:***REMOVED***"h-12***REMOVED***text-sm***REMOVED***group-data-[collapsible=icon]:!p-0",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***defaultVariants:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant:***REMOVED***"default",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size:***REMOVED***"default",
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED***}
)

const***REMOVED***SidebarMenuButton***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLButtonElement,
***REMOVED******REMOVED***React.ComponentProps<"button">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***asChild?:***REMOVED***boolean
***REMOVED******REMOVED******REMOVED******REMOVED***isActive?:***REMOVED***boolean
***REMOVED******REMOVED******REMOVED******REMOVED***tooltip?:***REMOVED***string***REMOVED***|***REMOVED***React.ComponentProps<typeof***REMOVED***TooltipContent>
***REMOVED******REMOVED***}***REMOVED***&***REMOVED***VariantProps<typeof***REMOVED***sidebarMenuButtonVariants>
>(
***REMOVED******REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***asChild***REMOVED***=***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isActive***REMOVED***=***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant***REMOVED***=***REMOVED***"default",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size***REMOVED***=***REMOVED***"default",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***tooltip,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...props
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***ref
***REMOVED******REMOVED***)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***Comp***REMOVED***=***REMOVED***asChild***REMOVED***?***REMOVED***Slot***REMOVED***:***REMOVED***"button"
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***isMobile,***REMOVED***state***REMOVED***}***REMOVED***=***REMOVED***useSidebar()

***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***button***REMOVED***=***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Comp
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="menu-button"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-size={size}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-active={isActive}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(sidebarMenuButtonVariants({***REMOVED***variant,***REMOVED***size***REMOVED***}),***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED***)

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!tooltip)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***button
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***tooltip***REMOVED***===***REMOVED***"string")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***tooltip***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***children:***REMOVED***tooltip,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Tooltip>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<TooltipTrigger***REMOVED***asChild>{button}</TooltipTrigger>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<TooltipContent
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***side="right"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***align="center"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hidden={state***REMOVED***!==***REMOVED***"collapsed"***REMOVED***||***REMOVED***isMobile}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...tooltip}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Tooltip>
***REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED***}
)
SidebarMenuButton.displayName***REMOVED***=***REMOVED***"SidebarMenuButton"

const***REMOVED***SidebarMenuAction***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLButtonElement,
***REMOVED******REMOVED***React.ComponentProps<"button">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***asChild?:***REMOVED***boolean
***REMOVED******REMOVED******REMOVED******REMOVED***showOnHover?:***REMOVED***boolean
***REMOVED******REMOVED***}
>(({***REMOVED***className,***REMOVED***asChild***REMOVED***=***REMOVED***false,***REMOVED***showOnHover***REMOVED***=***REMOVED***false,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***Comp***REMOVED***=***REMOVED***asChild***REMOVED***?***REMOVED***Slot***REMOVED***:***REMOVED***"button"

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Comp
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="menu-action"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"absolute***REMOVED***right-1***REMOVED***top-1.5***REMOVED***flex***REMOVED***aspect-square***REMOVED***w-5***REMOVED***items-center***REMOVED***justify-center***REMOVED***rounded-md***REMOVED***p-0***REMOVED***text-sidebar-foreground***REMOVED***outline-none***REMOVED***ring-sidebar-ring***REMOVED***transition-transform***REMOVED***hover:bg-sidebar-accent***REMOVED***hover:text-sidebar-accent-foreground***REMOVED***focus-visible:ring-2***REMOVED***peer-hover/menu-button:text-sidebar-accent-foreground***REMOVED***[&>svg]:size-4***REMOVED***[&>svg]:shrink-0",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Increases***REMOVED***the***REMOVED***hit***REMOVED***area***REMOVED***of***REMOVED***the***REMOVED***button***REMOVED***on***REMOVED***mobile.
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"after:absolute***REMOVED***after:-inset-2***REMOVED***after:md:hidden",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"peer-data-[size=sm]/menu-button:top-1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"peer-data-[size=default]/menu-button:top-1.5",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"peer-data-[size=lg]/menu-button:top-2.5",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group-data-[collapsible=icon]:hidden",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***showOnHover***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group-focus-within/menu-item:opacity-100***REMOVED***group-hover/menu-item:opacity-100***REMOVED***data-[state=open]:opacity-100***REMOVED***peer-data-[active=true]/menu-button:text-sidebar-accent-foreground***REMOVED***md:opacity-0",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarMenuAction.displayName***REMOVED***=***REMOVED***"SidebarMenuAction"

const***REMOVED***SidebarMenuBadge***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="menu-badge"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"absolute***REMOVED***right-1***REMOVED***flex***REMOVED***h-5***REMOVED***min-w-5***REMOVED***items-center***REMOVED***justify-center***REMOVED***rounded-md***REMOVED***px-1***REMOVED***text-xs***REMOVED***font-medium***REMOVED***tabular-nums***REMOVED***text-sidebar-foreground***REMOVED***select-none***REMOVED***pointer-events-none",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"peer-hover/menu-button:text-sidebar-accent-foreground***REMOVED***peer-data-[active=true]/menu-button:text-sidebar-accent-foreground",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"peer-data-[size=sm]/menu-button:top-1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"peer-data-[size=default]/menu-button:top-1.5",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"peer-data-[size=lg]/menu-button:top-2.5",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group-data-[collapsible=icon]:hidden",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
SidebarMenuBadge.displayName***REMOVED***=***REMOVED***"SidebarMenuBadge"

const***REMOVED***SidebarMenuSkeleton***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLDivElement,
***REMOVED******REMOVED***React.ComponentProps<"div">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***showIcon?:***REMOVED***boolean
***REMOVED******REMOVED***}
>(({***REMOVED***className,***REMOVED***showIcon***REMOVED***=***REMOVED***false,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***Random***REMOVED***width***REMOVED***between***REMOVED***50***REMOVED***to***REMOVED***90%.
***REMOVED******REMOVED***const***REMOVED***width***REMOVED***=***REMOVED***React.useMemo(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***`${Math.floor(Math.random()***REMOVED*******REMOVED***40)***REMOVED***+***REMOVED***50}%`
***REMOVED******REMOVED***},***REMOVED***[])

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="menu-skeleton"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("rounded-md***REMOVED***h-8***REMOVED***flex***REMOVED***gap-2***REMOVED***px-2***REMOVED***items-center",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{showIcon***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="size-4***REMOVED***rounded-md"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="menu-skeleton-icon"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="h-4***REMOVED***flex-1***REMOVED***max-w-[--skeleton-width]"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="menu-skeleton-text"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***style={
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"--skeleton-width":***REMOVED***width,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***as***REMOVED***React.CSSProperties
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***)
})
SidebarMenuSkeleton.displayName***REMOVED***=***REMOVED***"SidebarMenuSkeleton"

const***REMOVED***SidebarMenuSub***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLUListElement,
***REMOVED******REMOVED***React.ComponentProps<"ul">
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<ul
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="menu-sub"
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"mx-3.5***REMOVED***flex***REMOVED***min-w-0***REMOVED***translate-x-px***REMOVED***flex-col***REMOVED***gap-1***REMOVED***border-l***REMOVED***border-sidebar-border***REMOVED***px-2.5***REMOVED***py-0.5",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group-data-[collapsible=icon]:hidden",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
SidebarMenuSub.displayName***REMOVED***=***REMOVED***"SidebarMenuSub"

const***REMOVED***SidebarMenuSubItem***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLLIElement,
***REMOVED******REMOVED***React.ComponentProps<"li">
>(({***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***<li***REMOVED***ref={ref}***REMOVED***{...props}***REMOVED***/>)
SidebarMenuSubItem.displayName***REMOVED***=***REMOVED***"SidebarMenuSubItem"

const***REMOVED***SidebarMenuSubButton***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLAnchorElement,
***REMOVED******REMOVED***React.ComponentProps<"a">***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***asChild?:***REMOVED***boolean
***REMOVED******REMOVED******REMOVED******REMOVED***size?:***REMOVED***"sm"***REMOVED***|***REMOVED***"md"
***REMOVED******REMOVED******REMOVED******REMOVED***isActive?:***REMOVED***boolean
***REMOVED******REMOVED***}
>(({***REMOVED***asChild***REMOVED***=***REMOVED***false,***REMOVED***size***REMOVED***=***REMOVED***"md",***REMOVED***isActive,***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***Comp***REMOVED***=***REMOVED***asChild***REMOVED***?***REMOVED***Slot***REMOVED***:***REMOVED***"a"

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Comp
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-sidebar="menu-sub-button"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-size={size}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-active={isActive}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***h-7***REMOVED***min-w-0***REMOVED***-translate-x-px***REMOVED***items-center***REMOVED***gap-2***REMOVED***overflow-hidden***REMOVED***rounded-md***REMOVED***px-2***REMOVED***text-sidebar-foreground***REMOVED***outline-none***REMOVED***ring-sidebar-ring***REMOVED***hover:bg-sidebar-accent***REMOVED***hover:text-sidebar-accent-foreground***REMOVED***focus-visible:ring-2***REMOVED***active:bg-sidebar-accent***REMOVED***active:text-sidebar-accent-foreground***REMOVED***disabled:pointer-events-none***REMOVED***disabled:opacity-50***REMOVED***aria-disabled:pointer-events-none***REMOVED***aria-disabled:opacity-50***REMOVED***[&>span:last-child]:truncate***REMOVED***[&>svg]:size-4***REMOVED***[&>svg]:shrink-0***REMOVED***[&>svg]:text-sidebar-accent-foreground",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"data-[active=true]:bg-sidebar-accent***REMOVED***data-[active=true]:text-sidebar-accent-foreground",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size***REMOVED***===***REMOVED***"sm"***REMOVED***&&***REMOVED***"text-xs",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size***REMOVED***===***REMOVED***"md"***REMOVED***&&***REMOVED***"text-sm",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"group-data-[collapsible=icon]:hidden",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
})
SidebarMenuSubButton.displayName***REMOVED***=***REMOVED***"SidebarMenuSubButton"

export***REMOVED***{
***REMOVED******REMOVED***Sidebar,
***REMOVED******REMOVED***SidebarContent,
***REMOVED******REMOVED***SidebarFooter,
***REMOVED******REMOVED***SidebarGroup,
***REMOVED******REMOVED***SidebarGroupAction,
***REMOVED******REMOVED***SidebarGroupContent,
***REMOVED******REMOVED***SidebarGroupLabel,
***REMOVED******REMOVED***SidebarHeader,
***REMOVED******REMOVED***SidebarInput,
***REMOVED******REMOVED***SidebarInset,
***REMOVED******REMOVED***SidebarMenu,
***REMOVED******REMOVED***SidebarMenuAction,
***REMOVED******REMOVED***SidebarMenuBadge,
***REMOVED******REMOVED***SidebarMenuButton,
***REMOVED******REMOVED***SidebarMenuItem,
***REMOVED******REMOVED***SidebarMenuSkeleton,
***REMOVED******REMOVED***SidebarMenuSub,
***REMOVED******REMOVED***SidebarMenuSubButton,
***REMOVED******REMOVED***SidebarMenuSubItem,
***REMOVED******REMOVED***SidebarProvider,
***REMOVED******REMOVED***SidebarRail,
***REMOVED******REMOVED***SidebarSeparator,
***REMOVED******REMOVED***SidebarTrigger,
***REMOVED******REMOVED***useSidebar,
}
