import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"

const***REMOVED***Table***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLTableElement,
***REMOVED******REMOVED***React.HTMLAttributes<HTMLTableElement>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<div***REMOVED***className="relative***REMOVED***w-full***REMOVED***overflow-auto">
***REMOVED******REMOVED******REMOVED******REMOVED***<table
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("w-full***REMOVED***caption-bottom***REMOVED***text-sm",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***</div>
))
Table.displayName***REMOVED***=***REMOVED***"Table"

const***REMOVED***TableHeader***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLTableSectionElement,
***REMOVED******REMOVED***React.HTMLAttributes<HTMLTableSectionElement>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<thead***REMOVED***ref={ref}***REMOVED***className={cn("[&_tr]:border-b",***REMOVED***className)}***REMOVED***{...props}***REMOVED***/>
))
TableHeader.displayName***REMOVED***=***REMOVED***"TableHeader"

const***REMOVED***TableBody***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLTableSectionElement,
***REMOVED******REMOVED***React.HTMLAttributes<HTMLTableSectionElement>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<tbody
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("[&_tr:last-child]:border-0",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
TableBody.displayName***REMOVED***=***REMOVED***"TableBody"

const***REMOVED***TableFooter***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLTableSectionElement,
***REMOVED******REMOVED***React.HTMLAttributes<HTMLTableSectionElement>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<tfoot
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"border-t***REMOVED***bg-muted/50***REMOVED***font-medium***REMOVED***[&>tr]:last:border-b-0",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
TableFooter.displayName***REMOVED***=***REMOVED***"TableFooter"

const***REMOVED***TableRow***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLTableRowElement,
***REMOVED******REMOVED***React.HTMLAttributes<HTMLTableRowElement>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<tr
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"border-b***REMOVED***transition-colors***REMOVED***hover:bg-muted/50***REMOVED***data-[state=selected]:bg-muted",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
TableRow.displayName***REMOVED***=***REMOVED***"TableRow"

const***REMOVED***TableHead***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLTableCellElement,
***REMOVED******REMOVED***React.ThHTMLAttributes<HTMLTableCellElement>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<th
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"h-12***REMOVED***px-4***REMOVED***text-left***REMOVED***align-middle***REMOVED***font-medium***REMOVED***text-muted-foreground***REMOVED***[&:has([role=checkbox])]:pr-0",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
TableHead.displayName***REMOVED***=***REMOVED***"TableHead"

const***REMOVED***TableCell***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLTableCellElement,
***REMOVED******REMOVED***React.TdHTMLAttributes<HTMLTableCellElement>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<td
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("p-4***REMOVED***align-middle***REMOVED***[&:has([role=checkbox])]:pr-0",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
TableCell.displayName***REMOVED***=***REMOVED***"TableCell"

const***REMOVED***TableCaption***REMOVED***=***REMOVED***React.forwardRef<
***REMOVED******REMOVED***HTMLTableCaptionElement,
***REMOVED******REMOVED***React.HTMLAttributes<HTMLTableCaptionElement>
>(({***REMOVED***className,***REMOVED***...props***REMOVED***},***REMOVED***ref)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED***<caption
***REMOVED******REMOVED******REMOVED******REMOVED***ref={ref}
***REMOVED******REMOVED******REMOVED******REMOVED***className={cn("mt-4***REMOVED***text-sm***REMOVED***text-muted-foreground",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED***/>
))
TableCaption.displayName***REMOVED***=***REMOVED***"TableCaption"

export***REMOVED***{
***REMOVED******REMOVED***Table,
***REMOVED******REMOVED***TableHeader,
***REMOVED******REMOVED***TableBody,
***REMOVED******REMOVED***TableFooter,
***REMOVED******REMOVED***TableHead,
***REMOVED******REMOVED***TableRow,
***REMOVED******REMOVED***TableCell,
***REMOVED******REMOVED***TableCaption,
}
